Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2018-12, with the labels that each got.

#123 Update examples to use 1.12.3
  README.md
  cmd/clusterctl/examples/openstack/centos/machines.yaml.template
  cmd/clusterctl/examples/openstack/centos/provider-components.yaml.template
  cmd/clusterctl/examples/openstack/ubuntu/machines.yaml.template
  cmd/clusterctl/examples/openstack/ubuntu/provider-components.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/S

#97 Add rudimentary cloud.conf support.
  cmd/clusterctl/examples/openstack/centos/provider-components.yaml.template
  cmd/clusterctl/examples/openstack/generate-yaml.sh
  cmd/clusterctl/examples/openstack/ubuntu/provider-components.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#128 Fixes some minor bugs and unclear syntax
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#129 Return uuids at getNetworkIDsByFilter
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#135 Move to https://github.com/mikefarah/yq
  cmd/clusterctl/examples/openstack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#141 Explicitly require OS_CLOUD to be set
  cmd/clusterctl/examples/openstack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#144 Add clusterctl created files to .gitignore
  cmd/clusterctl/.gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#145 Move from glog to klog
  Gopkg.lock
  Gopkg.toml
  cmd/manager/main.go
  pkg/cloud/openstack/clients/machineservice.go
  pkg/cloud/openstack/cluster/actuator.go
  pkg/cloud/openstack/deployer.go
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#146 Re-apply of new yq usage
  cmd/clusterctl/examples/openstack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#142 Use realpath for path comparison in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#137 Pass machine config into VM startup script template
  pkg/cloud/openstack/machine/machineScript.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#147 Update cluster api
  Gopkg.lock
  Gopkg.toml
  cmd/clusterctl/examples/openstack/generate-yaml.sh
  vendor/sigs.k8s.io/cluster-api/.github/ISSUE_TEMPLATE/bug_report.md
  vendor/sigs.k8s.io/cluster-api/.github/ISSUE_TEMPLATE/feature_request.md
  vendor/sigs.k8s.io/cluster-api/Gopkg.lock
  vendor/sigs.k8s.io/cluster-api/Gopkg.toml
  vendor/sigs.k8s.io/cluster-api/Makefile
  vendor/sigs.k8s.io/cluster-api/README.md
  vendor/sigs.k8s.io/cluster-api/WORKSPACE
  vendor/sigs.k8s.io/cluster-api/config/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/config/default/kustomization.yaml
  vendor/sigs.k8s.io/cluster-api/config/default/manager_image_patch.yaml
  vendor/sigs.k8s.io/cluster-api/hack/update-bazel.sh
  vendor/sigs.k8s.io/cluster-api/hack/verify-bazel.sh
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/defaults.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/sync.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#160 Turn on automatic reauth for OpenStack client
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#136 Conf from secret
  Gopkg.lock
  config/rbac/rbac_role.yaml
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/clients/machineservice.go
  pkg/cloud/openstack/cluster/actuator.go
  pkg/cloud/openstack/machine/actuator.go
  pkg/cloud/openstack/types.go
  pkg/controller/add_cluster.go
  pkg/controller/add_machine.go
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#165 Disable ufw on ubuntu #149
  cmd/clusterctl/examples/openstack/ubuntu/provider-components.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/S
