Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2018-11, with the labels that each got.

#90 Let users select provider OS
  cmd/clusterctl/examples/openstack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#89 Generate bootstrap token
  Gopkg.lock
  Gopkg.toml
  pkg/bootstrap/token.go
  pkg/bootstrap/token_test.go
  pkg/cloud/openstack/machineactuator.go
  vendor/k8s.io/cluster-bootstrap/LICENSE
  vendor/k8s.io/cluster-bootstrap/token/api/doc.go
  vendor/k8s.io/cluster-bootstrap/token/api/types.go
  vendor/k8s.io/cluster-bootstrap/token/util/helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#91 OS_CLOUD templating re-work
  cmd/clusterctl/examples/openstack/generate-yaml.sh
  config/manager/manager.yaml
  config/manager/manager_template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#95 Added Role to kube-system to allow CAP-OS to create secrets
  config/rbac/secrets_role.yaml
  config/rbac/secrets_role_binding.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#94 Cluster actuator
  Gopkg.lock
  pkg/apis/openstackproviderconfig/group.go
  pkg/apis/openstackproviderconfig/v1alpha1/register.go
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/cluster/actuator.go
  pkg/cloud/openstack/clusteractuator.go
  pkg/cloud/openstack/deployer.go
  pkg/cloud/openstack/machine/actuator.go
  pkg/cloud/openstack/machine/instancestatus.go
  pkg/cloud/openstack/machine/machineScript.go
  pkg/cloud/openstack/machine/machinesetup/config_types.go
  pkg/controller/add_cluster.go
  pkg/controller/add_machine.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#101 Don't update the cluster status
  pkg/cloud/openstack/cluster/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#103 Decoding machine status fails during machine Update calls
  pkg/cloud/openstack/machine/instancestatus.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#105 Fix README.md
  README.md
  cmd/clusterctl/examples/openstack/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#111 Switch yaml to sigs.k8s.io/yaml
  Gopkg.lock
  Gopkg.toml
  pkg/apis/openstackproviderconfig/v1alpha1/register.go
  pkg/cloud/openstack/machine/machinesetup/config_types.go
  vendor/sigs.k8s.io/yaml/.gitignore
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/CONTRIBUTING.md
  vendor/sigs.k8s.io/yaml/LICENSE
  vendor/sigs.k8s.io/yaml/OWNERS
  vendor/sigs.k8s.io/yaml/README.md
  vendor/sigs.k8s.io/yaml/RELEASE.md
  vendor/sigs.k8s.io/yaml/SECURITY_CONTACTS
  vendor/sigs.k8s.io/yaml/code-of-conduct.md
  vendor/sigs.k8s.io/yaml/fields.go
  vendor/sigs.k8s.io/yaml/yaml.go
  vendor/sigs.k8s.io/yaml/yaml_go110.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#117 Fixup logs
  Gopkg.lock
  Gopkg.toml
  cmd/manager/main.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#119 Upgrade docker version on node
  cmd/clusterctl/examples/openstack/ubuntu/provider-components.yaml.template
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS
