Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2018-07, with the labels that each got.

#2 Fix import path: cluster-provider-api-openstack -> cluster-api-provider-openstack
  Makefile
  README.md
  RELEASE.md
  cloud/openstack/clients/machineservice.go
  cloud/openstack/machineactuator.go
  cloud/openstack/openstackproviderconfig/v1alpha1/register.go
  cmd/openstack-machine-controller/main.go
  images/machine-controller/Dockerfile
Labels: cncf-cla: yes, size/S

#11 Readme add "getting start"
  README.md
  clusterctl/examples/openstack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#13 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
