Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2018-10, with the labels that each got.

#24 Be explicit that minikube <= 0.28.0 is required.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#26 Check for errors on StatusUpdate and DeleteKeyPair
  cloud/openstack/machineactuator.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#27 return AssociateFloatingIP error only if != nil
  cloud/openstack/machineactuator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#28 iterate over all instance interfaces
  cloud/openstack/machineactuator.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#25 Fix indentation for floatingIP in example machines.yaml
  clusterctl/examples/openstack/machines.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#33 Add Github PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#30 Adding flaper87 as a cluster-api-openstack-maintainer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#35 Call Parse() to avoid noisy logs
  cmd/machine-controller/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#38 Run gofmt
  cloud/openstack/deployer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#39 Use users $HOME/.ssh for openstack_tmp SSH key
  cloud/openstack/deployer.go
  clusterctl/examples/openstack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#47 Fix openstackprovierconfig registration
  pkg/apis/openstackproviderconfig/v1alpha1/register.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#52 golint has moved!
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#40 Use NewDeploymentClient() to get DeploymentClient
  pkg/cloud/openstack/deployer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#53 Update README
  README.md
  cmd/clusterctl/examples/openstack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#54 Add chaosaffe to cluster-api-openstack-maintainers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#55 Make providerConfig keys consistent
  cmd/clusterctl/examples/openstack/machines.yaml.template
  config/crd/openstackproviderconfig_v1alpha1.yaml
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#57 Add sed Darwin/Linux switch to generate-yaml.sh
  cmd/clusterctl/examples/openstack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#58 Update cluster-api version
  vendor/sigs.k8s.io/cluster-api/Gopkg.lock
  vendor/sigs.k8s.io/cluster-api/Makefile
  vendor/sigs.k8s.io/cluster-api/OWNERS_ALIASES
  vendor/sigs.k8s.io/cluster-api/README.md
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/README.md
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/bootstrap/minikube/minikube.go
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/cmd/create_cluster.go
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/cmd/delete_cluster.go
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/testdata/create-cluster-no-args-invalid-flag.golden
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/testdata/create-cluster-no-args.golden
  vendor/sigs.k8s.io/cluster-api/config/crds/cluster_v1alpha1_machinedeployment.yaml
  vendor/sigs.k8s.io/cluster-api/scripts/ci-is-vendor-in-sync.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#56 add cluster controller
  pkg/cloud/openstack/clusteractuator.go
  pkg/controller/add_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#60 Recommend using v1.12.1
  README.md
  cmd/clusterctl/examples/openstack/machines.yaml.template
  cmd/clusterctl/examples/openstack/provider-components.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#63 Use the startUp script as template
  cmd/clusterctl/examples/openstack/provider-components.yaml.template
  pkg/cloud/openstack/machineScript.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#67 Remove hardcoded machine username
  cmd/clusterctl/examples/openstack/machines.yaml.template
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/deployer.go
  pkg/cloud/openstack/machineactuator.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#70 Let clientconfig create the AuthOptions instance
  config/manager/manager.yaml
  pkg/cloud/openstack/clients/machineservice.go
  pkg/cloud/openstack/clients/machineservice_test.go
  pkg/cloud/openstack/machineactuator.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#75 Get only the last line of the kubeadm token cmd
  pkg/cloud/openstack/machineactuator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#76 Add missing kernel modules to the node
  cmd/clusterctl/examples/openstack/provider-components.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#77 Use 443 until cluster-api is fixed
  cmd/clusterctl/examples/openstack/provider-components.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#73 Updated to include clouds.yaml instructions
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#83 Fix shabang of generate-yaml.sh
  cmd/clusterctl/examples/openstack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#84 Add templates for CentOS
  cmd/clusterctl/examples/openstack/centos/cluster.yaml.template
  cmd/clusterctl/examples/openstack/centos/machines.yaml.template
  cmd/clusterctl/examples/openstack/centos/provider-components.yaml.template
  cmd/clusterctl/examples/openstack/generate-yaml.sh
  cmd/clusterctl/examples/openstack/ubuntu/cluster.yaml.template
  cmd/clusterctl/examples/openstack/ubuntu/machines.yaml.template
  cmd/clusterctl/examples/openstack/ubuntu/provider-components.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/L

#80 Generate-yaml sets OS_CLOUD in provider manager to the OS_CLOUD in its working env
  README.md
  cmd/clusterctl/examples/openstack/generate-yaml.sh
  config/manager/manager_template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#87 Support paths with spaces.
  cmd/clusterctl/examples/openstack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/M
