Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2019-07, with the labels that each got.

#384 Add MachineDeployment template
  cmd/clusterctl/examples/openstack/generate-yaml.sh
  cmd/clusterctl/examples/openstack/machine-deployment.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#379 Improvements in config.md file
  docs/config.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#376 move from deployment to statefulset
  config/kustomization.yaml
  config/manager/statefulset.yaml
  overlays-config/coreos/manager/deployment.yaml
  overlays-config/generic/manager/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#390 Fix centos create generate issue
  cmd/clusterctl/examples/openstack/provider-component/user-data/centos/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#388 Fix klog issue
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#393 Added Stefan Büringer (sbueringer) to be a reviewer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#396 Fix failed to create cluster
  cmd/clusterctl/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#389 Update kubeadm to 1.15
  README.md
  cmd/clusterctl/examples/openstack/machine-deployment.yaml.template
  cmd/clusterctl/examples/openstack/machines.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/S

#397 Add tip on fixing node xxxx not found
  docs/trouble_shooting.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#403 move port from 6443 to 443
  pkg/deployer/deployer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#404 fix generate-yaml by escaping newlines
  cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/master.yaml
  pkg/cloud/openstack/services/userdata/machinescript.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#405 update doc for ssh key creation
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#406 Fix kustomize
  cmd/clusterctl/examples/openstack/provider-component/cluster-api/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#408 add documentation on how to use custom CAs
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#414 Add providerstatus
  config/crds/openstackproviderconfig_v1alpha1_openstackmachineproviderstatus.yaml
  config/kustomization.yaml
  config/rbac/rbac_role.yaml
  pkg/apis/openstackproviderconfig/v1alpha1/register.go
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#365 Support fixedRouterIP
  config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderspec.yaml
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/openstack/services/networking/router.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#412 Create kubeconfig for each cluster in reconcile function
  Gopkg.lock
  cmd/clusterctl/examples/openstack/cluster.yaml
  config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderspec.yaml
  config/rbac/rbac_role.yaml
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/cluster/actuator.go
  pkg/deployer/deployer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#409 modify doc to add machineset
  docs/config.md
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/M
