Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2019-09, with the labels that each got.

#456 Add sbueringer to cluster-api-openstack-maintainers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#459 Fix api port
  controllers/openstackcluster_controller.go
  examples/cluster/cluster.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#449 Hostname missing in /etc/hosts file in openstack instance
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/worker-user-data.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#462 Pr finalize v1alpha2
  Dockerfile
  Makefile
  README.md
  config/default/manager_image_patch.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  examples/controlplane/controlplane.yaml
  examples/generate.sh
  examples/machinedeployment/machinedeployment.yaml
  go.sum
  pkg/cloud/services/provider/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#460 Add release process for staging images
  cloudbuild.yaml
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#466 Stop Instance creation on invalid Network spec
  pkg/cloud/services/compute/instance.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#465 Fix cacert issue
  examples/controlplane/controlplane.yaml
  examples/generate.sh
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#468 fix certificate indentation
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#469 Remove duplicate create
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
