Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2019-03, with the labels that each got.

#240 Fix a log about no external network
  pkg/cloud/openstack/clients/networkservice.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#250 use template instead of hard code in the doc
  docs/config.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#253 Adjust log for update action
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#245 Change calico version to v3.5
  cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/master-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#248 Fix the cluster name
  pkg/cloud/openstack/cluster/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#249 Tags and Metadata
  Gopkg.lock
  cmd/clusterctl/examples/openstack/machines.yaml.template
  config/crds/openstackproviderconfig_v1alpha1_openstackproviderspec.yaml
  docs/config.md
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/openstack/clients/machineservice.go
  vendor/github.com/gophercloud/gophercloud/auth_options.go
  vendor/github.com/gophercloud/gophercloud/auth_result.go
  vendor/github.com/gophercloud/gophercloud/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/auth_env.go
  vendor/github.com/gophercloud/gophercloud/openstack/client.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/microversions.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tenants/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/results.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/github.com/gophercloud/gophercloud/service_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#254 Add config drive support
  config/crds/openstackproviderconfig_v1alpha1_openstackproviderspec.yaml
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#260 Enhance log of VM skip delete
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#261 make generate-yaml.sh work from anywhere
  cmd/clusterctl/examples/openstack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#269 Added kind example for openstack provider.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#259 Fix permission of cloud.conf
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#255 fix spec generatation
  config/crds/openstackproviderconfig_v1alpha1_openstackproviderspec.yaml
  docs/config.md
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#278 Migrated kubeadm config to v1beta1 for kubeadm 1.14
  cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/master-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/worker-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/worker-user-data.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#276 Add more reviewers for the repository
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#277 Added "new" node taints to tolerations
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#284 Fixed usage of bootstrap token
  cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/worker-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/worker-user-data.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#283 Added template for issue and features.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, cncf-cla: yes, lgtm, size/M
