Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2019-10, with the labels that each got.

#474 Pr refactor doc
  CONTRIBUTING.md
  Makefile
  README.md
  RELEASE.md
  config/default/manager_image_patch.yaml
  docs/config.md
  docs/development.md
  docs/getting-started.md
  docs/troubleshooting.md
  examples/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#479 LeaderElectionID should be unique
  Makefile
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#482 update calico version to v3.8 (#481)
  cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/master-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/master.yaml
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#476 Generate seperate multi-node and single-node yaml
  docs/config.md
  examples/README.md
  examples/cluster/multi-node/cluster.yaml
  examples/cluster/multi-node/kustomization.yaml
  examples/cluster/multi-node/kustomizeconfig.yaml
  examples/cluster/single-node/cluster.yaml
  examples/cluster/single-node/kustomization.yaml
  examples/cluster/single-node/kustomizeconfig.yaml
  examples/controlplane/multi-node/controlplane.yaml
  examples/controlplane/multi-node/kustomization.yaml
  examples/controlplane/multi-node/kustomizeconfig.yaml
  examples/controlplane/single-node/controlplane.yaml
  examples/controlplane/single-node/kustomization.yaml
  examples/controlplane/single-node/kustomizeconfig.yaml
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#486 Upgrade gophercloud to v0.4.0
  go.mod
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#488 finalize doc & examples for v0.2.0
  .gitignore
  Makefile
  RELEASE.md
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  config/default/manager_pull_policy.yaml
  config/manager/manager.yaml
  docs/getting-started.md
  examples/cluster/multi-node/cluster.yaml
  examples/cluster/single-node/cluster.yaml
  examples/controlplane/multi-node/controlplane.yaml
  examples/controlplane/single-node/controlplane.yaml
  examples/machinedeployment/machinedeployment.yaml
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M
