Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2019-08, with the labels that each got.

#401 Adds Managed APIServer Loadbalancer
  Gopkg.lock
  config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderspec.yaml
  config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderstatus.yaml
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/openstack/cluster/actuator.go
  pkg/cloud/openstack/machine/actuator.go
  pkg/cloud/openstack/services/networking/loadbalancer.go
  pkg/cloud/openstack/services/networking/service.go
  pkg/deployer/deployer.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/l7policies/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/l7policies/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/l7policies/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/l7policies/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/listeners/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/listeners/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/listeners/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/monitors/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/monitors/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/monitors/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/monitors/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/pools/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/pools/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/pools/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/pools/urls.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#420 Add notes for using custom pod network CIDR
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#423 Add a log indicating lb member creation
  pkg/cloud/openstack/services/networking/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#424 Rename network prefix
  pkg/cloud/openstack/services/networking/service.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#426 Use Octavia
  config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderspec.yaml
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/cluster/actuator.go
  pkg/cloud/openstack/machine/actuator.go
  pkg/cloud/openstack/services/loadbalancer/loadbalancer.go
  pkg/cloud/openstack/services/loadbalancer/service.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/urls.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XL

#430 Fix delete pool lead to panic
  pkg/cloud/openstack/machine/actuator.go
  pkg/cloud/openstack/services/loadbalancer/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#431 update doc about delete cluster
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#437 Add tips for https cacert
  docs/trouble_shooting.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#438 follow up PR 421 to make ubuntu and centos work
  cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/worker-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/worker-user-data.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#440 Fix clouds.yaml link and add some notes in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#441 fixed quotes in coreos userdata
  cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/master.yaml
  cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/worker.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#443 use env for bash
  cmd/clusterctl/examples/openstack/generate-yaml.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/master.yaml
  hack/update-gofmt.sh
  hack/verify-golint.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#434 Add delete loadbalancer support
  pkg/cloud/openstack/cluster/actuator.go
  pkg/cloud/openstack/services/loadbalancer/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#447 Backport changes from master to release-0.1
  README.md
  cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/master.yaml
  cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/worker.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#448 Update doc about release-0.1 and master branch
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#435 Pr create floating ip on demand
  pkg/cloud/openstack/machine/actuator.go
  pkg/cloud/openstack/services/loadbalancer/loadbalancer.go
  pkg/cloud/openstack/services/networking/floatingip.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#444 fix empty default values if imageRepository is not set
  pkg/cloud/openstack/services/userdata/kubeadm.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#451 some minor fix during test on ubuntu
  samples/generate-yaml.sh
  samples/templates/cluster.yaml
  samples/templates/machines.yaml
  samples/templates/user-data/centos/templates/master-user-data.sh
  samples/templates/user-data/ubuntu/templates/master-user-data.sh
  samples/templates/user-data/ubuntu/templates/master-user-data.sh.template
  samples/templates/user-data/ubuntu/templates/worker-user-data.sh.template
  samples/templates/user-data/ubuntu/worker-user-data.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#454 Fix generation issue
  examples/provider-components/manager_tolerations_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
