Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2019-06, with the labels that each got.

#359 change base image to fix security issue
  cmd/manager/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#361 Fix usage of verify property from clouds.yaml
  pkg/cloud/openstack/clients/machineservice.go
  pkg/cloud/openstack/cluster/actuator.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#369 Fix event creation
  config/rbac/rbac_role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#371 make TokenTTL configurable through CLI
  cmd/manager/main.go
  pkg/cloud/openstack/machine/actuator.go
  pkg/cloud/openstack/options/options.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#372 Support OpenStack Stein
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#348 Add Development Guide
  README.md
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#374 Set GO111MODULE=off when make build
  Makefile
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#357 update kustomize template to fit for latest kustomize
  Makefile
  README.md
  cmd/clusterctl/examples/openstack/README.md
  cmd/clusterctl/examples/openstack/generate-yaml.sh
  cmd/clusterctl/examples/openstack/provider-component/clouds-secrets/kustomization.yaml
  cmd/clusterctl/examples/openstack/provider-component/cluster-api/kustomization.yaml
  cmd/clusterctl/examples/openstack/provider-component/user-data/centos/kustomization.yaml
  cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/kustomization.yaml
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
