Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2019-04, with the labels that each got.

#289 Fix security group rules example in docs/config.md
  docs/config.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#285 Added compatibility information to README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#297 Delete project_name from clouds.yaml.
  pkg/cloud/openstack/clients/clouds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#151 Add boot from volume support
  Gopkg.lock
  cmd/clusterctl/examples/openstack/machines.yaml.template
  config/crds/openstackproviderconfig_v1alpha1_openstackproviderspec.yaml
  docs/config.md
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/clients/machineservice.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/urls.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#287 Upgrade kubeadm version
  cmd/clusterctl/examples/openstack/machines.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#266 fix template after change securityGroups from string to SecurityGroupParam
  cmd/clusterctl/examples/openstack/machines.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#299 Adding steps for how to use existing cluster as bootstrap cluster.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#293 disable swap in master and node
  cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/master-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/worker-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/worker-user-data.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#291 Enabled kubeadm debug log for better troubleshooting.
  cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/master-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/worker-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/worker-user-data.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#281 Clearer tagging UI and Bugfix
  Gopkg.lock
  cmd/clusterctl/examples/openstack/cluster.yaml
  cmd/clusterctl/examples/openstack/machines.yaml.template
  config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderspec.yaml
  config/crds/openstackproviderconfig_v1alpha1_openstackproviderspec.yaml
  docs/config.md
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/openstack/clients/machineservice.go
  pkg/cloud/openstack/cluster/actuator.go
  pkg/cloud/openstack/machine/actuator.go
  vendor/github.com/gophercloud/gophercloud/internal/pkg.go
  vendor/github.com/gophercloud/gophercloud/internal/util.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/types.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/urls.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#310 Adding gyliu513 and jichenjc as approvers.
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#300 Add Kubeadm and Kubelet versions info in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#303 Added coreos to openstack provider.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#309 Add ConfigDrive in zz_generated.deepcopy.go
  Makefile
  pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#305 add Dockerfile of clusterctl
  Makefile
  cmd/clusterctl/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#257 Add doc for generate generate-yaml.sh
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#302 Add tips for trouble shooting
  README.md
  docs/trouble_shooting.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#313 Added toc to md for better readability.
  CONTRIBUTING.md
  README.md
  cmd/clusterctl/examples/openstack/README.md
  code-of-conduct.md
  docs/config.md
  docs/trouble_shooting.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#314 update README to add coreos support and kustomize required
  README.md
  cmd/clusterctl/examples/openstack/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#316 Fix permission of cloud.conf (644->600)
  cmd/clusterctl/examples/openstack/generate-yaml.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/common.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#319 v1beta1 -> v1 for Deployment template
  config/manager/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#320 Update keystone port number in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#321 Use apps/v1 for deployment apiVersion
  overlays-config/coreos/manager/deployment.yaml
  overlays-config/generic/manager/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#322 Add generate yaml test
  Makefile
  README.md
  cmd/clusterctl/examples/openstack/README.md
  cmd/clusterctl/examples/openstack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#326 Deployment V1 Spec required the selector
  config/manager/deployment.yaml
  overlays-config/coreos/manager/deployment.yaml
  overlays-config/generic/manager/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#328 MERCURIAL is not need by Makefile.
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#329 change to use v1alpha1.SecurityGroupParam
  cmd/clusterctl/examples/openstack/machines.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#262 Add configuration for create timeout
  docs/config.md
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#332 use the same version of kubectl with kubelet
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#224 Support keystone with certificate
  cmd/clusterctl/examples/openstack/generate-yaml.sh
  cmd/clusterctl/examples/openstack/provider-component/clouds-secrets/kustomization.yaml
  cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/master-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/worker-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/common.yaml
  cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/master.yaml
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/worker-user-data.sh
  config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderspec.yaml
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/openstack/clients/machineservice.go
  pkg/cloud/openstack/cluster/actuator.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#336 Adding cacert to clouds.yaml.
  pkg/cloud/openstack/clients/clouds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#335 init-cloud exit if the selinux did not enabled
  cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/master-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/worker-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh
  cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/worker-user-data.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#241 Delete SecurityGroups from cluster
  pkg/cloud/openstack/clients/secgroupservice.go
  pkg/cloud/openstack/cluster/actuator.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
