Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2019-01, with the labels that each got.

#168 Fix incorrect debug info after generate-yaml
  cmd/clusterctl/examples/openstack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#150 Basic cluster reconciler
  Gopkg.lock
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/openstack/clients/networkservice.go
  pkg/cloud/openstack/cluster/actuator.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/urls.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#172 Remove MasterEndpoint string in favour of a function
  cmd/clusterctl/examples/openstack/centos/provider-components.yaml.template
  cmd/clusterctl/examples/openstack/ubuntu/provider-components.yaml.template
  pkg/cloud/openstack/machine/machineScript.go
  pkg/cloud/openstack/machine/machineScript_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#148 Add doc for some tips on floatingip settings
  README.md
  docs/config.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#173 Get user-data/startupScripts from secrets
  cmd/clusterctl/examples/openstack/centos/machines.yaml.template
  cmd/clusterctl/examples/openstack/centos/master-user-data.sh
  cmd/clusterctl/examples/openstack/centos/provider-components.yaml.template
  cmd/clusterctl/examples/openstack/centos/worker-user-data.sh
  cmd/clusterctl/examples/openstack/generate-yaml.sh
  cmd/clusterctl/examples/openstack/ubuntu/machines.yaml.template
  cmd/clusterctl/examples/openstack/ubuntu/master-user-data.sh
  cmd/clusterctl/examples/openstack/ubuntu/provider-components.yaml.template
  cmd/clusterctl/examples/openstack/ubuntu/worker-user-data.sh
  config/manager/manager.yaml
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/machine/actuator.go
  pkg/cloud/openstack/machine/machinesetup/config_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#177 Grant provider access to status subresource in clusters
  config/rbac/rbac_role.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#179 Use gopkg.in/yaml.v2 for clientconfig objects
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#176 Don't fail on missing sshkeys
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#180 Fix worker-user-data template for CentOS
  cmd/clusterctl/examples/openstack/centos/worker-user-data.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#182 Don't require kubelet version to be set
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#181 Add the filter key to the network's CRD entry
  config/crd/openstackproviderconfig_v1alpha1.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#184 Fix clusterctl workflow
  README.md
  cmd/clusterctl/examples/openstack/centos/machines.yaml.template
  cmd/clusterctl/examples/openstack/centos/master-user-data.sh
  cmd/clusterctl/examples/openstack/generate-yaml.sh
  cmd/clusterctl/examples/openstack/ubuntu/machines.yaml.template
  cmd/clusterctl/examples/openstack/ubuntu/master-user-data.sh
  cmd/clusterctl/examples/openstack/ubuntu/worker-user-data.sh
  pkg/cloud/openstack/deployer.go
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#186 Fixed bootstrapping of CentOS machine
  cmd/clusterctl/examples/openstack/centos/master-user-data.sh
  cmd/clusterctl/examples/openstack/centos/worker-user-data.sh
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#178 Tagging of created network resources
  Gopkg.lock
  pkg/cloud/openstack/clients/networkservice.go
  pkg/cloud/openstack/cluster/actuator.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/urls.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#188 add UserDataSecret into deepcopy file
  pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#191 Improve generator readme
  cmd/clusterctl/examples/openstack/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#192 Remove need to mount ssh keys in the manager container
  cmd/clusterctl/examples/openstack/centos/provider-components.yaml.template
  cmd/clusterctl/examples/openstack/generate-yaml.sh
  cmd/clusterctl/examples/openstack/ubuntu/provider-components.yaml.template
  config/manager/manager.yaml
  pkg/cloud/openstack/clients/machineservice.go
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#194 Use corev1.SecretReference for CloudsSecrets too
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/clients/machineservice.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#201 Add chrigl to cluster-api-openstack-maintainers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#200 Check that the old VM has been deleted before creating a new VM
  pkg/cloud/openstack/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#208 Remove unnecessary equal signs
  docs/config.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#206 Update README.md to add deleting the kubeconfig file step in the Cluster Deletion section
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#212 Updated slack link to our own channel
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#210 Fix --bootstrap-flags vm-driver=kvm2 flag
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#214 Disabled auto generation of rbac ClusterRoles
  Makefile
  config/rbac/rbac_role_binding.yaml
  pkg/cloud/openstack/cluster/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#216 Configure DNS Nameservers for created network
  config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderspec.yaml
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
  pkg/cloud/openstack/clients/networkservice.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#218 Make auto generate crds generate openstackproviderspec
  config/crds/openstackproviderconfig_v1alpha1_openstackproviderspec.yaml
  pkg/apis/openstackproviderconfig/v1alpha1/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M
