Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2020-12, with the labels that each got.

#692 🐛 Delete spec.disableServerTags of OpenStackCluster
  templates/cluster-template-external-cloud-provider.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#697 📖 fix getting log
  docs/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#696 🏃 Add OpenStack version to bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#693 Fix nil pointer error for Network
  controllers/openstackcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#705 🐛 Fix SecurityGroupInUse error
  pkg/cloud/services/compute/instance.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#700 :bug: Add SecurityGroup to Loadbalancerport when not using octavia
  controllers/openstackcluster_controller.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/service.go
  pkg/cloud/services/networking/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#708 🏃 Move ncdc to emeritus status
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#711 🏃Refactor create, delete instance
  pkg/cloud/services/compute/bastion.go
  pkg/cloud/services/compute/instance.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#710 🏃 Refactor loadbalancer package
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/service.go
  pkg/cloud/services/networking/floatingip.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#714 :bug: Fix domain_name and domain_id usage in env.rc
  templates/env.rc
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#686 move from 0.3.1 to 0.3.3 in the CI test
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#716 Fix ca-file path in env.rc
  templates/env.rc
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
