Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2020-08, with the labels that each got.

#573 ✨Add external network discovery
  api/v1alpha3/openstackcluster_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/networking/floatingip.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
  templates/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#608 Update e2e test and document of non lb case
  .zuul/playbooks/run.yaml
  Makefile
  docs/configuration.md
  hack/ci/e2e-conformance.sh
  templates/cluster-template-without-lb.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#615 🏃 Bump Cluster-API to v0.3.8
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#613 🏃 e2e test uses official Kubernetes version
  .zuul/playbooks/run.yaml
  Makefile
  hack/ci/e2e-conformance.sh
  hack/ci/e2e-conformance/e2e-conformance_patch.yaml.tpl
Labels: approved, cncf-cla: yes, lgtm, size/L

#607 ✨ Use OpenStack key pair instead of KubeadmConfig spec
  Makefile
  docs/configuration.md
  hack/ci/e2e-conformance.sh
  hack/ci/e2e-conformance/kustomization.yaml
  templates/cluster-template-external-cloud-provider.yaml
  templates/cluster-template-without-lb.yaml
  templates/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#611 🏃 Update template for the external cloud provider
  templates/cluster-template-external-cloud-provider.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#616 🐛 Fix e2e test Kubernetes official binaries version
  Makefile
  hack/ci/e2e-conformance/e2e-conformance_patch.yaml.tpl
Labels: approved, cncf-cla: yes, lgtm, size/L

#606 switch to no-admin for CI test
  .zuul/playbooks/run.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#599 Add application cred usage
  docs/configuration.md
  templates/create_cloud_conf.sh
  templates/env.rc
Labels: approved, cncf-cla: yes, lgtm, size/M

#596 Remove Tag creation for ports and add description for it
  api/v1alpha3/openstackcluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  docs/configuration.md
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
  templates/cluster-template-without-lb.yaml
  templates/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#618 Rename to capoerrors
  pkg/cloud/services/networking/network.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#620 🐛 Fix get openstackcluster to show ENDPOINT value
  api/v1alpha3/openstackcluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#623 🏃 Add CAPO version to github issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#624 nit: update name of `get` output for openstackmachine
  api/v1alpha3/openstackmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
