Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2020-02, with the labels that each got.

#504 Add clusterctl-settings.json
  clusterctl-settings.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#506 Proposal: 🏃golang: update go to 1.13.7
  Dockerfile
  go.mod
  hack/ensure-go.sh
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#507 Proposal 🏃: dependencies: bump some dependencies to the latest stable
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#508 ✨health: add liveness and readiness probes
  config/manager/manager.yaml
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#509 📖 Update installation link
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#498 Add alternative to OS image
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
