Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2020-01, with the labels that each got.

#495 install kustomize via install script instead of go get
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#494 enhance doc regarding to manually delete cluster
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#496 Adopt PR icons
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#497 Add additional description for DNS
  api/v1alpha2/openstackcluster_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#502 :bug: deduplicate machine tags prior to openstack API apply call
  .golangci.yml
  pkg/cloud/services/compute/instance.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#500 🐛 don't require cacert in cloud.yaml
  pkg/cloud/services/provider/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
