Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2020-09, with the labels that each got.

#625 cleanup keys params
  api/v1alpha3/openstackcluster_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#617 Add tags to status
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  controllers/openstackcluster_controller.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#629 📖 Fix Link for external openstack template
  docs/external-cloud-provider.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#632 CI: Wget kubernetes binary be quiet
  hack/ci/e2e-conformance/e2e-conformance_patch.yaml.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#619 ✨ Add bastion host to login the nodes and update non HA template
  .zuul/playbooks/run.yaml
  Makefile
  api/v1alpha3/openstackcluster_types.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  controllers/openstackcluster_controller.go
  docs/configuration.md
  hack/ci/e2e-conformance.sh
  hack/ci/e2e-conformance/e2e-conformance_patch.yaml.tpl
  pkg/cloud/services/compute/bastion.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/networking/securitygroups.go
  templates/cluster-template-without-lb.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#637 default concurrent reconcile from 1 to 10
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#638 Add version into log
  main.go
  version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/M
