Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2020-04, with the labels that each got.

#535 🏃 Add Stein to v1alpha3 tested version
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#536 Add 1.18 support into list
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#534 🐛 Fix cluster-template.yaml
  pkg/cloud/services/networking/securitygroups.go
  templates/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#538 🐛 Fix updating to Cluster API v0.3.3
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#539 🏃 Pr add prow test scripts
  Makefile
  scripts/ci-build.sh
  scripts/ci-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#537 Add availability zone to be used by controller plane
  api/v1alpha3/openstackcluster_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  controllers/openstackcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#542 🐛 remove docker-build from build test
  scripts/ci-build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#540 🐛 e2e test: switch to -bazel folder because bin folder has been removed
  hack/ci/e2e-conformance/e2e-conformance_patch.yaml.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#541 Add additional info when error occur
  pkg/cloud/services/provider/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#545 📖 Update Configuration doc
  docs/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#549 reviewers: remove flaper87
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#550 🐛 Set up OPENSTACK_CLOUD environment variable in env.rc
  templates/env.rc
Labels: approved, cncf-cla: yes, lgtm, size/XS

#548 🐛 enable managedAPIServerLoadBalancer w/ existing network
  controllers/openstackcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
