Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2020-07, with the labels that each got.

#579 🐛 Fix README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#576 📖 Update Required Configuration
  docs/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#575 Add doc tip for floating ip
  docs/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#583 report error if security group not exist
  pkg/cloud/services/compute/instance.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#592 Add event for seucrity group
  pkg/cloud/services/networking/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#585 nit: Add default egress rule description
  pkg/cloud/services/networking/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#593 Add more logs for debug purpose
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
  pkg/cloud/services/networking/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#595 ✨ Use external cloud provider
  docs/external-cloud-provider.md
  templates/cluster-template-external-cloud-provider.yaml
  templates/create_cloud_conf.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#597 🏃 Add hidekazuna to reviewer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#598 🐛Update mtu size in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#600 📖 Add reference to the external cloud provider doc
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#602 nit: replace return with exit
  templates/create_cloud_conf.sh
  templates/env.rc
Labels: approved, cncf-cla: yes, lgtm, size/S
