Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2020-11, with the labels that each got.

#656 🐛 Update reference to the latest version of CAPO v0.3.1
  Makefile
  clusterctl-settings.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#662 Add root volume support (put root volume into instance create param)
  pkg/cloud/services/compute/instance.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#664 Add doc update for boot from volume case
  docs/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#665 fix location for env.rc file
  docs/configuration.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#669 🐛 Fix to delete only automatically created floating IPs
  controllers/openstackmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#672 nit: remove duplicate blanks
  pkg/cloud/services/compute/instance.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#666 ✨ Add support for Tilt
  .gitignore
  docs/development.md
  tilt-provider.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#677 📖 Update how to retrieve kubeconfig
  docs/external-cloud-provider.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#671 set openstack cluster status for Bastion
  controllers/openstackcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#673 Move log to creating place
  controllers/openstackmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#680 Switch CI from U to V release
  .zuul/playbooks/run.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#586 Add openstack ussuri into support list
  README.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/S

#682 Add cluster-template-external-cloud-provider.yaml into release doc
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#683 move to capi 0.3.11
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#688 update Make method to avoid mismatch
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#690 ✨ Align flag names with upstream Kubernetes components
  config/manager/manager.yaml
  config/manager/manager_auth_proxy_patch.yaml
  config/webhook/manager_webhook_patch.yaml
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/S
