Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2020-03, with the labels that each got.

#510 📖 Fix development.md
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#512 🐛 Fix PROVIDERID
  controllers/openstackmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#516 🐛 fixup Makefile, should fix image build on master
  Makefile
  PROJECT
  api/v1alpha2/groupversion_info.go
  api/v1alpha2/openstackcluster_types.go
  api/v1alpha2/openstackmachine_types.go
  api/v1alpha2/openstackmachinetemplate_types.go
  api/v1alpha2/types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cloudbuild.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  controllers/suite_test.go
  docs/config.md
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#520 🐛 PR for final bugfixes before the v1alpha3 release
  Makefile
  RELEASE.md
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  go.mod
  go.sum
  hack/ci/e2e-conformance.sh
  metadata.yaml
  templates/env.rc
Labels: approved, cncf-cla: yes, lgtm, size/L

#521 ⚠️ fixup namespace handling in 0.3.0
  RELEASE.md
  templates/cluster-template-without-lb.yaml
  templates/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#529 avoid basename usage to avoid source action failure
  templates/env.rc
Labels: approved, cncf-cla: yes, lgtm, size/XS

#527 Fix cacert issue
  templates/env.rc
Labels: approved, cncf-cla: yes, lgtm, size/XS

#531 ✨ Add ServerGroupID to OpenStackMachineSpec
  api/v1alpha3/openstackmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  pkg/cloud/services/compute/instance.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#522 ✨ Delete router/network/subnet
  controllers/openstackcluster_controller.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#532 🏃 Update to cluster-api v0.3.3, controller-tools v0.2.8 and controller-runtime v0.5.2
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#523 🐛 use sec groups from the current project, wait for lb from last reconcile
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/service.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/provider/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#491 🏃 Add Zuul jobs for e2e conformance tests
  .zuul.yaml
  .zuul/playbooks/run.yaml
  Makefile
  hack/ci/ci-bootstrap.yaml
  hack/ci/e2e-conformance.sh
  hack/ci/e2e-conformance/.gitignore
  hack/ci/e2e-conformance/e2e-conformance_patch.yaml.tpl
  hack/ci/e2e-conformance/kustomization.yaml
  hack/ensure-kind.sh
  hack/ensure-kubectl.sh
  hack/ensure-kustomize.sh
  templates/kustomization.yaml
  templates/kustomizeversions.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL
