Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2021-07, with the labels that each got.

#922 🏃 use amphora image from GCS in e2e tests
  hack/ci/devstack-default-cloud-init.yaml.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#928 Rename master to main
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#923 🏃 sync linter settings with cluster-api repo and fix findings
  .golangci.yml
  api/v1alpha3/types.go
  api/v1alpha4/openstackmachinetemplate_webhook.go
  api/v1alpha4/openstackmachinetemplate_webhook_test.go
  api/v1alpha4/types.go
  controllers/openstackmachine_controller.go
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/provider/provider.go
  pkg/metrics/metrics.go
  pkg/record/recorder.go
  test/e2e/shared/common.go
  test/e2e/shared/kubernetesversions/template.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#925 ✨ add description and tag to floating ips
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/networking/floatingip.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#930 reassociate Floating IP if first associate fails
  controllers/openstackmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#932 ✨ Add GET gophercloud metrics
  pkg/cloud/services/compute/availabilityzone.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/networking/floatingip.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/provider/provider.go
  pkg/metrics/metrics.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#893 Add failure fields in OpestackCluster status section
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/openstackcluster_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  controllers/openstackcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#939 Revert "reassociate Floating IP if first associate fails"
  controllers/openstackmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#941 🐛 Remove the ttl flag from sshuttle invocation
  hack/ci/devstack-on-aws-project-install.sh
  hack/ci/devstack-on-gce-project-install.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#905 Use the kubernetesversions package of the cluster-api repo again
  go.mod
  go.sum
  test/e2e/shared/kubernetesversions/data/debian_injection_script_control_plane.envsubst.sh
  test/e2e/shared/kubernetesversions/data/debian_injection_script_worker.envsubst.sh
  test/e2e/shared/kubernetesversions/data/kustomization.yaml
  test/e2e/shared/kubernetesversions/template.go
  test/e2e/shared/suite.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#938 🐛 Wait for ports creation in ports e2e test
  test/e2e/suites/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#937 ✨ Add conversion for SecretReference to string
  api/v1alpha3/conversion.go
  api/v1alpha3/openstackcluster_types.go
  api/v1alpha3/openstackmachine_types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/identity_types.go
  api/v1alpha4/openstackcluster_types.go
  api/v1alpha4/openstackcluster_webhook.go
  api/v1alpha4/openstackmachine_types.go
  api/v1alpha4/openstackmachine_webhook.go
  api/v1alpha4/openstackmachinetemplate_webhook.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/manifests.yaml
  pkg/cloud/services/provider/provider.go
  templates/cluster-template-external-cloud-provider.yaml
  templates/cluster-template-without-lb.yaml
  templates/cluster-template.yaml
  test/e2e/data/infrastructure-openstack/cluster-template-external-cloud-provider.yaml
  test/e2e/data/infrastructure-openstack/cluster-template-without-lb.yaml
  test/e2e/data/infrastructure-openstack/cluster-template.yaml
  test/e2e/suites/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#944 📖 Adjust README.md to fit v0.4.0 and bump k8s to v1.21.3
  README.md
  docs/book/src/clusteropenstack/configuration.md
  test/e2e/data/e2e_conf.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#933 ✨ Add OpenStackClusterTemplates Type
  PROJECT
  api/v1alpha4/openstackclustertemplate_types.go
  api/v1alpha4/openstackclustertemplate_webhook.go
  api/v1alpha4/openstackmachinetemplate_webhook.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_openstackclustertemplates.yaml
  config/crd/patches/webhook_in_openstackclustertemplates.yaml
  config/webhook/manifests.yaml
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#945 ✨ Fix Webhook names for OpenStackMachineTemplate and OpenStackCluster
  api/v1alpha4/openstackcluster_webhook.go
  api/v1alpha4/openstackmachinetemplate_webhook.go
  config/webhook/manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#946 📖 improve release documentation
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#935 ✨ Add mock client and 2 tests for networking package
  go.mod
  go.sum
  pkg/cloud/services/networking/client.go
  pkg/cloud/services/networking/floatingip.go
  pkg/cloud/services/networking/floatingip_test.go
  pkg/cloud/services/networking/mock_networking/client_mock.go
  pkg/cloud/services/networking/mock_networking/doc.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/networking/service.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#947 ✨ Do not update fip if its already mapped correct
  pkg/cloud/services/networking/floatingip.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#953 🐛 openstackcluster reconciliation: reset .Status.failureMessage and .Status.FailureReason on success
  controllers/openstackcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#955 ✨ Add webhook readiness and health checks
  go.mod
  go.sum
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#921 ✨ Apply Port Security to Ports
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
