Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2021-06, with the labels that each got.

#891 Fix error logging for OpenStack instance creation
  pkg/cloud/services/compute/instance.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#876 ✨ Add feature to create ports with custom options
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/openstackmachine_types.go
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#897 :sparkles: add predicates.ResourceIsNotExternallyManaged to cluster controller
  controllers/openstackcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#900 📖 Document custom ports feature
  docs/book/src/clusteropenstack/configuration.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#901 ✨ Upgrade CAPI to v0.4.0-beta.0
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
  templates/cluster-template-external-cloud-provider.yaml
  templates/cluster-template-without-lb.yaml
  templates/cluster-template.yaml
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/infrastructure-openstack/cluster-template-external-cloud-provider.yaml
  test/e2e/data/infrastructure-openstack/cluster-template-without-lb.yaml
  test/e2e/data/infrastructure-openstack/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#902 🐛 fix release staging target
  hack/image-patch/pull-policy-patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#894 Add resource shortNames
  api/v1alpha3/openstackcluster_types.go
  api/v1alpha3/openstackmachine_types.go
  api/v1alpha3/openstackmachinetemplate_types.go
  api/v1alpha4/openstackcluster_types.go
  api/v1alpha4/openstackmachine_types.go
  api/v1alpha4/openstackmachinetemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#904 🐛 Fix doc about external cloud provider
  docs/book/src/topics/external-cloud-provider.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#903 🐛 fixup release targets and update doc accordingly
  Makefile
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#908 🏃 Add test for custom port options feature
  test/e2e/shared/openstack.go
  test/e2e/suites/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#916 🐛 Don't log nil error when AuthInfo is not set
  pkg/cloud/services/compute/service.go
  pkg/cloud/services/networking/service.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#915 📖 Upgrading a cluster without LBaaS is not supported
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#919 ✨Update CAPI to v0.4.0
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL
