Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2021-10, with the labels that each got.

#1004 ✨Return all NodeAddresses in OpenStackMachine.Status.Addresses
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_types.go
  pkg/cloud/services/compute/instance_types_test.go
  test/e2e/data/infrastructure-openstack/cluster-template-multi-network.yaml
  test/e2e/shared/common.go
  test/e2e/shared/defaults.go
  test/e2e/shared/openstack.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1010 🏃update e2e container to latest cluster-api
  Makefile
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#1019 ✨ controllers: replace context.TODO with real context objects
  controllers/openstackmachine_controller.go
Labels: size/S, cncf-cla: yes, approved, lgtm
