Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2021-05, with the labels that each got.

#853 ✨ adjust loadbalancer wait.Backoff
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#860 ✨ Add gophercloud request logs, fix contexts
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/provider/provider.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#861 Upgrade to latest CAPI version (2021-05-07)
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  go.mod
  go.sum
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  test/e2e/data/e2e_conf.yaml
  test/e2e/shared/kubernetesversions/data/debian_injection_script_control_plane.envsubst.sh
  test/e2e/shared/kubernetesversions/data/debian_injection_script_worker.envsubst.sh
  test/e2e/shared/kubernetesversions/data/kustomization.yaml
  test/e2e/shared/kubernetesversions/template.go
  test/e2e/suites/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#866 📖 Add doc related to log level
  docs/book/src/clusteropenstack/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#867 Add more logs for LB creation
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#862 🏃 Add some events and refactor related to instance
  controllers/openstackmachine_controller.go
  pkg/cloud/services/compute/bastion.go
  pkg/cloud/services/compute/instance.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#873 Add chrischdi as reviewer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#874 Add seanschneeweiss as reviewer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#871 🏃 Refactor: use Service struct field more
  pkg/cloud/services/compute/bastion.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/service.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/networking/floatingip.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#872 🏃 Validate OpenStackMachineTemplate spec.template.spec immutability
  api/v1alpha4/openstackmachinetemplate_webhook.go
  api/v1alpha4/openstackmachinetemplate_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#870 Add description to resource capi created
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
  pkg/utils/names/names.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/M

#863 Add metrics of gophercloud (POST,UPDATE and DELETE) actions
  go.mod
  main.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/networking/floatingip.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
  pkg/cloud/services/networking/securitygroups.go
  pkg/metrics/metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#881 honor server group ID parm
  pkg/cloud/services/compute/instance.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#869 Add some events related to load balancer
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#880 🐛 Fix event of associate/disassociate floating IP
  pkg/cloud/services/networking/floatingip.go
Labels: approved, cncf-cla: yes, lgtm, size/M
