Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2021-03, with the labels that each got.

#762 Fix a doc typo
  docs/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#766 🏃 Update OWNERS files
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/M

#767 Fix gate issue (test failure)
  go.sum
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#761 🐛Remove start.sh and restart.sh
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#757 Add support for failureDomain (AZ) for bastion
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  controllers/openstackcluster_controller.go
  hack/ci/e2e-conformance/e2e-conformance_patch.yaml.tpl
  pkg/cloud/services/compute/bastion.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#775 🐛 Fix release 0.3 gate
  go.sum
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#776 Add support for failureDomain (AZ) for bastion
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  controllers/openstackcluster_controller.go
  hack/ci/e2e-conformance/e2e-conformance_patch.yaml.tpl
  pkg/cloud/services/compute/bastion.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#781 📖 Update configuration doc
  docs/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#759 🏃 migrate conformance test to Prow
  .dockerignore
  .zuul.yaml
  .zuul/playbooks/run.yaml
  Makefile
  docs/configuration.md
  hack/boilerplate/boilerplate.py
  hack/boilerplate/boilerplate.py.txt
  hack/boskos.py
  hack/ci/.gitignore
  hack/ci/e2e-conformance-gcp-cloud-init.yaml.tpl
  hack/ci/e2e-conformance-gcp-prepare.sh
  hack/ci/e2e-conformance.sh
  hack/ci/e2e-conformance/e2e-conformance_patch.yaml.tpl
  hack/verify-boilerplate.sh
  scripts/ci-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#779 ✨ Update klog dependency to v2
  go.mod
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#773 ✨ pkg/cloud/services/networking/securitygroups.go reimplement reconcilation
  pkg/cloud/services/networking/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#786 🏃 Add todos to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#789 Update development guide
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#787 release-0.3: cherry pick migrate OpenLab conformance test to Prow
  .dockerignore
  .gitignore
  .zuul.yaml
  .zuul/playbooks/run.yaml
  Makefile
  docs/configuration.md
  hack/boilerplate/boilerplate.py
  hack/boilerplate/boilerplate.py.txt
  hack/boskos.py
  hack/ci/.gitignore
  hack/ci/e2e-conformance-gcp-cloud-init.yaml.tpl
  hack/ci/e2e-conformance-gcp-prepare.sh
  hack/ci/e2e-conformance.sh
  hack/ci/e2e-conformance/e2e-conformance_patch.yaml.tpl
  hack/verify-boilerplate.sh
  scripts/ci-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#791 🏃 goimports: fix import order, add local-prefix to linter
  .golangci.yml
  api/v1alpha3/conversion.go
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  controllers/suite_test.go
  main.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/service.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/service.go
  pkg/cloud/services/networking/floatingip.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/networking/service.go
  pkg/cloud/services/provider/provider.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#793 🏃 Remove disablePortSecurity: false from template
  templates/cluster-template-external-cloud-provider.yaml
  templates/cluster-template-without-lb.yaml
  templates/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#795 🏃 Remove useOctavia from nonha template
  templates/cluster-template-without-lb.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#792 🏃 update yq commands to support yq V4
  templates/create_cloud_conf.sh
  templates/env.rc
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#802 🐛 Make conversion-gen output location explicit
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#799 🐛 InstanceExists should not do substring search on name
  pkg/cloud/services/compute/instance.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#709 🏃 [0.2] Move ncdc to emeritus status
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#803 🏃 Bump ginkgo version
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#806 🏃 Remove unused release note section in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#807 📖 Update links for filing new issue
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#797 🏃 Update golangci-lint and fix most of the linter issues
  .golangci.yml
  Makefile
  api/v1alpha3/groupversion_info.go
  api/v1alpha3/openstackcluster_types.go
  api/v1alpha3/openstackmachine_types.go
  api/v1alpha3/openstackmachinetemplate_types.go
  api/v1alpha3/types.go
  api/v1alpha4/groupversion_info.go
  api/v1alpha4/openstackcluster_types.go
  api/v1alpha4/openstackmachine_types.go
  api/v1alpha4/openstackmachine_webhook.go
  api/v1alpha4/openstackmachinetemplate_types.go
  api/v1alpha4/openstackmachinetemplate_webhook.go
  api/v1alpha4/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  controllers/suite_test.go
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
  pkg/cloud/services/compute/bastion.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/service.go
  pkg/cloud/services/networking/floatingip.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/networking/service.go
  pkg/cloud/services/provider/provider.go
  pkg/utils/errors/errors.go
  test/e2e/shared/cluster.go
  test/e2e/shared/common.go
  test/e2e/shared/context.go
  test/e2e/shared/defaults.go
  test/e2e/shared/exec.go
  test/e2e/shared/openstack.go
  test/e2e/shared/openstack_test.go
  test/e2e/shared/suite.go
  test/e2e/suites/conformance/conformance_suite_test.go
  test/e2e/suites/conformance/conformance_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#809 🐛 fix post-cluster-api-provider-openstack-push-images
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#810 🐛 Fix configuration.md about bastion
  docs/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#811 fix post-cluster-api-provider-openstack-push-images and add post-submit manifests
  Makefile
  hack/image-patch/kustomization.yaml
  hack/image-patch/pull-policy-patch.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#812 🏃 Improve ci script patching
  test/e2e/data/ci-artifacts-platform-kustomization.yaml
  test/e2e/data/infrastructure-openstack/cluster-template-external-cloud-provider.yaml
  test/e2e/data/infrastructure-openstack/cluster-template.yaml
  test/e2e/shared/kubernetesversions/data/debian_injection_script_control_plane.envsubst.sh
  test/e2e/shared/kubernetesversions/data/debian_injection_script_worker.envsubst.sh
  test/e2e/shared/kubernetesversions/data/kustomization.yaml.tpl
  test/e2e/shared/kubernetesversions/template.go
  test/e2e/shared/suite.go
  test/e2e/shared/tmp_template.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#817 🐛 Delete bastion if basion.enabled=false
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/compute/bastion.go
  pkg/cloud/services/networking/floatingip.go
  pkg/cloud/services/networking/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#813 🏃 Remove neutron lbaas support
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/openstackcluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/service.go
  pkg/cloud/services/networking/securitygroups.go
  templates/cluster-template-external-cloud-provider.yaml
  templates/cluster-template.yaml
  test/e2e/data/infrastructure-openstack/cluster-template-external-cloud-provider.yaml
  test/e2e/data/infrastructure-openstack/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#815 🏃 Test openstack key in our e2e tests
  hack/ci/devstack-cloud-init.yaml.tpl
  test/e2e/data/ci-artifacts-platform-kustomization.yaml
  test/e2e/shared/common.go
  test/e2e/shared/exec.go
  test/e2e/shared/exec_test.go
  test/e2e/shared/openstack.go
Labels: approved, cncf-cla: yes, lgtm, size/L
