Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2021-08, with the labels that each got.

#924 🐛 Fix failure to create server with specified tags
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  docs/book/src/clusteropenstack/configuration.md
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/service.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#957 📖Fix broken link
  docs/book/src/clusteropenstack/configuration.md
  docs/book/src/topics/external-cloud-provider.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#962 🐛 ignore Conflict status in order to make instance able to detach interface
  pkg/cloud/services/compute/instance.go
  pkg/metrics/metrics.go
  pkg/utils/errors/errors.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#963 📖 Add netlify.toml to publish our book
  .gitignore
  netlify.toml
Labels: size/M, cncf-cla: yes, approved, lgtm

#958 📖Add port security doc
  docs/book/src/clusteropenstack/configuration.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#969 🐛 bump controller-runtime to 0.9.6 to fix webhook tls errors
  go.mod
  go.sum
Labels: size/M, cncf-cla: yes, approved, lgtm

#967 🏃Return error if instance go error
  pkg/cloud/services/compute/instance.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#970 update from v1alpha3 to v1alpha4 in Makefile
  Makefile
Labels: cncf-cla: yes, approved, size/XS, lgtm

#964 getOrCreatePort: add support to configure port Profile
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  docs/book/src/clusteropenstack/configuration.md
  pkg/cloud/services/compute/instance.go
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#960 ✨ Cleanup and refactor InstanceExists and DeleteInstance
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/compute/bastion.go
  pkg/cloud/services/compute/instance.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#971 :sparkles: Refactor: Don't use infrav1.Instance internally
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/compute/bastion.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_types.go
  test/e2e/shared/openstack.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#975 Add gc for error instance's port
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/compute/instance.go
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#977 Update flavor usage of e2e test
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#980 fix gate lint issue
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/zz_generated.deepcopy.go
  hack/boilerplate/boilerplate.py
  hack/tools/tools.go
  test/e2e/shared/cluster.go
  test/e2e/shared/common.go
  test/e2e/shared/context.go
  test/e2e/shared/defaults.go
  test/e2e/shared/exec.go
  test/e2e/shared/exec_test.go
  test/e2e/shared/openstack.go
  test/e2e/shared/openstack_test.go
  test/e2e/shared/suite.go
  test/e2e/suites/conformance/conformance_suite_test.go
  test/e2e/suites/conformance/conformance_test.go
  test/e2e/suites/e2e/e2e_suite_test.go
  test/e2e/suites/e2e/e2e_test.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#934 ✨ Allow Trunk configuration at a Port level
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  pkg/cloud/services/compute/instance.go
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test
