Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2021-09, with the labels that each got.

#978 only use loadbalaner reference if needed
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#986 :bug: Fix Conversion from alpha3 to alpha4
  api/v1alpha3/conversion.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#982 ✨Document running E2E tests locally
  docs/book/src/development/development.md
Labels: cncf-cla: yes, approved, size/L, lgtm

#989 ⚠️ Don't overwrite openstackcluster.status.network on reconciliation
  controllers/openstackcluster_controller.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#985 :bug: Add alpha3 Resources to Scheme
  main.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#950 🏃 Refactor all network client calls into networking package
  pkg/cloud/services/compute/bastion.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/service.go
  pkg/cloud/services/networking/client.go
  pkg/cloud/services/networking/mock_networking/client_mock.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/networking/trunk.go
Labels: cncf-cla: yes, approved, size/XL, lgtm, ok-to-test

#996 📖 Add book link to README
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#992 ✨Add InstanceStatus.AvailabilityZone()
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_types.go
  test/e2e/shared/openstack.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1002 🏃 Move deletePorts back to compute package
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/networking/port.go
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#998 :sparkles: Implement allowAllInClusterTraffic flag
  api/v1alpha4/openstackcluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  docs/book/src/clusteropenstack/configuration.md
  pkg/cloud/services/networking/securitygroups.go
  test/e2e/data/infrastructure-openstack/cluster-template-external-cloud-provider.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#973 :sparkles: Allow clusters without a floating IP for the API server
  api/v1alpha4/openstackcluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  docs/book/src/clusteropenstack/configuration.md
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/networking/network.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#1003 🏃 Standardize metrics in networking package
  pkg/cloud/services/networking/client.go
  pkg/cloud/services/networking/trunk.go
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1006 ✨Add webhook of openstackcluster, no update allowed for now
  api/v1alpha4/openstackcluster_webhook.go
  config/webhook/manifests.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#1012 ✨Allow update for some param only first time update
  api/v1alpha4/openstackcluster_webhook.go
  api/v1alpha4/openstackmachine_webhook.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#994 🐛 Don't make unnecessary REST API calls in getServerNetworks
  api/v1alpha4/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/networking/service.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1015 🏃 Bump calico from v3.18.1 to v3.20.1
  test/e2e/data/cni/calico.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XXL
