Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2022-01, with the labels that each got.

#1104 🐛update log to make it clear (LB member instead of LB)
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1102 📖nit: update doc to include spec
  docs/book/src/clusteropenstack/configuration.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1101 Allow image uuid to be used in instanceSpec
  api/v1alpha3/conversion.go
  api/v1alpha3/conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/conversion.go
  api/v1alpha4/conversion_test.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/openstackmachine_types.go
  api/v1beta1/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  pkg/cloud/services/compute/bastion.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/instance_types.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1095 Delete trunk on failure
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1107 🐛 Avoid replacing tags when no tags are provided.
  pkg/cloud/services/networking/service.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1030 ✨Cinder AZ and volume type support
  api/v1alpha3/conversion.go
  api/v1alpha3/conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/conversion.go
  api/v1alpha4/conversion_test.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  docs/book/src/clusteropenstack/configuration.md
  hack/ci/cloud-init/controller.yaml.tpl
  hack/ci/cloud-init/worker.yaml.tpl
  hack/ci/openstack.sh
  pkg/cloud/services/compute/client.go
  pkg/cloud/services/compute/client_mock.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/service.go
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/infrastructure-openstack/cluster-template-multi-az.yaml
  test/e2e/shared/defaults.go
  test/e2e/shared/openstack.go
  test/e2e/suites/e2e/e2e_suite_test.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1108 Document running CI devstack on CentOS
  docs/book/src/development/ci.md
  hack/ci/gce-project.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#1113 iamemilio resigns as a reviewer
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1112 Remove duplicate tags before making API calls
  pkg/cloud/services/networking/service.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#1115 🐛 Prevent creation of floating IPs when reconcile load balancer in non ACTIVE state
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test
