Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2022-03, with the labels that each got.

#1157 ✨Remove FIXME (adjust the comment and code both)
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/networking/port.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1150 🐛 api/v1beta1/openstackmachine_types.go: change errorReason/errorMessage to failureReason/failureMessage
  api/v1beta1/openstackmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1158 move CI to xena
  README.md
  hack/ci/cloud-init/controller.yaml.tpl
  hack/ci/create_devstack.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#1167 📖 add info about office hours to README and Book
  README.md
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#1165 🐛 Clean up removed AvailabilityZones from `OpenStackCluster.status.failureDomains`
  controllers/openstackcluster_controller.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1169 🐛 Bump CAPI version to fix cert-manager URL
  Makefile
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1170 🏃 sync OWNERS and OWNERS_ALIASES for v0.5 release branch
  OWNERS
  OWNERS_ALIASES
Labels: size/S, cncf-cla: yes, approved, lgtm

#1164 :bug: [v0.5.0] Prevent creation of floating IPs when reconcile load balancer in non ACTIVE state
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1168 Remove `internal` AZ special handling
  controllers/openstackcluster_controller.go
  docs/book/src/clusteropenstack/configuration.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1175 Fix flaky UT on gate
  pkg/cloud/services/networking/service.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1173 🐛 update logic to support more instance state
  api/v1alpha3/types.go
  api/v1alpha4/types.go
  controllers/openstackmachine_controller.go
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#1130 🐛 Delete trunk on failure
  pkg/cloud/services/compute/instance.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#1177 🐛 Fix event target of floating ip operations
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/networking/floatingip.go
  pkg/cloud/services/networking/floatingip_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1161 📖update doc to talk about microversion
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1172 Add unit test for trunk
  pkg/cloud/services/networking/trunk_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1179 ✨Export GetFloatingIP
  pkg/cloud/services/networking/floatingip.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1184 🐛 upgrade golangci-lint for go 1.18 support
  api/v1alpha3/openstackcluster_types.go
  api/v1alpha3/openstackmachine_types.go
  api/v1alpha4/openstackmachine_types.go
  api/v1beta1/openstackmachine_types.go
  go.mod
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/record/recorder.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1182 🐛 Address CVE-2022-21698
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1178 🏃 Add Scopes to pass data to services
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/service.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/service.go
  pkg/cloud/services/networking/floatingip.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/networking/service.go
  pkg/scope/scope.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1185 🐛 Install sshuttle using pip instead of from source
  hack/ci/create_devstack.sh
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1183 🏃 Enable controller tests
  Makefile
  controllers/suite_test.go
  scripts/go_install.sh
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#1190 🏃 Explain mutability of bastion configuration in CRD
  api/v1alpha3/openstackcluster_types.go
  api/v1alpha4/openstackcluster_types.go
  api/v1beta1/openstackcluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm
