Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2022-06, with the labels that each got.

#1243 cleanup: remove used file
  hack/update-gofmt.sh
  hack/verify-gofmt.sh
  hack/verify-golint.sh
Labels: cncf-cla: yes, approved, size/L, lgtm

#1258 :sparkles: bump golangci-lint version to v1.46.2
  hack/tools/go.mod
  hack/tools/go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm

#1247 ✨ Feature: restrict API Server LB access via IPs
  api/v1alpha3/conversion.go
  api/v1alpha3/conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/conversion.go
  api/v1alpha4/conversion_test.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha5/openstackcluster_webhook.go
  api/v1alpha5/openstackcluster_webhook_test.go
  api/v1alpha5/types.go
  api/v1alpha5/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  docs/book/src/clusteropenstack/configuration.md
  go.mod
  go.sum
  main.go
  pkg/cloud/services/loadbalancer/client.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
  pkg/cloud/services/loadbalancer/mock_loadbalancer/doc.go
  pkg/cloud/services/loadbalancer/mock_loadbalancer/loadbalancer_service_mock.go
  pkg/cloud/services/networking/router.go
  pkg/utils/openstack/loadbalancer.go
  pkg/utils/strings/strings.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL, ok-to-test

#1263 🐛 Make failure domain optional for OpenStackMachine
  controllers/openstackmachine_controller.go
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#1267 📖 Instance create timeout is in minutes
  docs/book/src/clusteropenstack/configuration.md
Labels: cncf-cla: yes, needs-ok-to-test, approved, size/XS, lgtm

#1268 nit:make event to log for already associated FIP
  pkg/cloud/services/networking/floatingip.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1275 update doc to reflect latest version, add helm link
  docs/book/src/topics/external-cloud-provider.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1277 use 1.24 as test env
  README.md
  docs/book/src/clusteropenstack/configuration.md
  test/e2e/data/e2e_conf.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1279 Add Age column for osc/osm
  api/v1alpha3/openstackcluster_types.go
  api/v1alpha3/openstackmachine_types.go
  api/v1alpha4/openstackcluster_types.go
  api/v1alpha4/openstackmachine_types.go
  api/v1alpha5/openstackcluster_types.go
  api/v1alpha5/openstackmachine_types.go
  api/v1alpha6/openstackcluster_types.go
  api/v1alpha6/openstackmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1260 🐛 delete port left over by err openstackmachine
  controllers/openstackcluster_controller.go
  pkg/cloud/services/networking/port.go
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1271 🌱 Generate cluster templates with kustomize
  Makefile
  common.mk
  kustomize/v1alpha5/default/cluster-template.yaml
  kustomize/v1alpha5/default/kustomization.yaml
  kustomize/v1alpha5/external-cloud-provider/kustomization.yaml
  kustomize/v1alpha5/external-cloud-provider/patch-ccm.yaml
  kustomize/v1alpha5/without-lb/kustomization.yaml
  kustomize/v1alpha5/without-lb/patch-without-lb.yaml
  kustomize/v1alpha6/default/cluster-template.yaml
  kustomize/v1alpha6/default/kustomization.yaml
  kustomize/v1alpha6/external-cloud-provider/kustomization.yaml
  kustomize/v1alpha6/external-cloud-provider/patch-ccm.yaml
  kustomize/v1alpha6/without-lb/kustomization.yaml
  kustomize/v1alpha6/without-lb/patch-without-lb.yaml
  templates/.gitignore
  templates/README.txt
  templates/cluster-template-without-lb.yaml
  test/e2e/data/infrastructure-openstack/.gitignore
  test/e2e/data/infrastructure-openstack/cluster-template-external-cloud-provider.yaml
  test/e2e/data/infrastructure-openstack/cluster-template-multi-az.yaml
  test/e2e/data/infrastructure-openstack/cluster-template-multi-network.yaml
  test/e2e/data/infrastructure-openstack/cluster-template-without-lb.yaml
  test/e2e/data/infrastructure-openstack/cluster-template.yaml
  test/e2e/data/kustomize/common-patches/cni.yaml
  test/e2e/data/kustomize/common-patches/kustomization.yaml
  test/e2e/data/kustomize/common-patches/patch-cluster.yaml
  test/e2e/data/kustomize/common-patches/patch-cni.yaml
  test/e2e/data/kustomize/default/kustomization.yaml
  test/e2e/data/kustomize/external-cloud-provider/ccm.yaml
  test/e2e/data/kustomize/external-cloud-provider/kustomization.yaml
  test/e2e/data/kustomize/external-cloud-provider/patch-allow-all-in-cluster-traffic.yaml
  test/e2e/data/kustomize/external-cloud-provider/patch-ccm.yaml
  test/e2e/data/kustomize/multi-az/kustomization.yaml
  test/e2e/data/kustomize/multi-az/patch-control-plane.yaml
  test/e2e/data/kustomize/multi-az/patch-machine-deployment.yaml
  test/e2e/data/kustomize/multi-az/patch-machine-template-control-plane.yaml
  test/e2e/data/kustomize/multi-az/patch-machine-template-worker.yaml
  test/e2e/data/kustomize/multi-network/kustomization.yaml
  test/e2e/data/kustomize/multi-network/patch-machine-template-networks.yaml
  test/e2e/data/kustomize/with-tags/kustomization.yaml
  test/e2e/data/kustomize/with-tags/patch-cluster.yaml
  test/e2e/data/kustomize/with-tags/patch-machine-template-control-plane.yaml
  test/e2e/data/kustomize/with-tags/patch-machine-template-worker.yaml
  test/e2e/data/kustomize/without-lb/kustomization.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1287 Fix generation of e2e-templates when running conformance tests
  Makefile
  hack/tools/Makefile
Labels: size/S, cncf-cla: yes, approved, lgtm
