Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2022-04, with the labels that each got.

#1187 ⚠️ move loadbalancer opts to struct
  api/v1alpha3/conversion.go
  api/v1alpha3/conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/conversion_test.go
  api/v1alpha4/openstackcluster_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/openstackcluster_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  templates/cluster-template-external-cloud-provider.yaml
  templates/cluster-template.yaml
  test/e2e/data/infrastructure-openstack/cluster-template-external-cloud-provider.yaml
  test/e2e/data/infrastructure-openstack/cluster-template-multi-az.yaml
  test/e2e/data/infrastructure-openstack/cluster-template-multi-network.yaml
  test/e2e/data/infrastructure-openstack/cluster-template.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#1191 ✨Refactor CreateInstance and CreateBastion
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  controllers/openstackmachine_controller_test.go
  pkg/cloud/services/compute/bastion.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/instance_types.go
  pkg/cloud/services/networking/securitygroups.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#1189 ✨ Support Application Credential auth
  README.md
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/service.go
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/networking/service.go
  pkg/cloud/services/provider/provider.go
  pkg/scope/scope.go
  test/e2e/shared/openstack.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1204 address CVE-2022-27191
  go.mod
  go.sum
Labels: size/S, cncf-cla: yes, approved, lgtm

#1208 :bug: fix tests in release-0.5
  .golangci.yml
  api/v1alpha3/openstackcluster_types.go
  api/v1alpha3/openstackmachine_types.go
  api/v1alpha4/openstackmachine_types.go
  go.mod
  hack/ci/create_devstack.sh
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/cloud/services/networking/router.go
  pkg/record/recorder.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#1205 🐛 address CVE-2022-27191
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1212 🏃 Add apricote as a reviewer
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1213 🏃Remove prankul88 as a reviewer
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1209 🐛 bump CAPI to v1.1.3
  Makefile
  README.md
  docs/book/src/clusteropenstack/configuration.md
  go.mod
  go.sum
  test/e2e/data/ccm/cloud-controller-manager.yaml
  test/e2e/data/cni/calico.yaml
  test/e2e/data/e2e_conf.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#1217 🐛 controllers/openstackcluster_controller.go fix nil pointer and dump openstack ports
  controllers/openstackcluster_controller.go
  test/e2e/shared/openstack.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1216 📖 Document CRD changes from v1alpha4 to v1alpha5
  docs/book/src/SUMMARY.md
  docs/book/src/topics/crd-changes/index.md
  docs/book/src/topics/crd-changes/v1alpha4-to-v1alpha5.md
Labels: cncf-cla: yes, approved, size/L, lgtm

#1200 🐛 always wait for active Loadbalancer after getOrCreate
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1223 🐛Fix conversion of boot from volume images
  api/v1alpha4/conversion.go
  api/v1alpha4/conversion_test.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#1226 🌱 Add release 0.6.x to metadata.yaml
  metadata.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1224 📖 allow up to 20 tabs in book
  docs/book/theme/css/general.css
Labels: size/S, cncf-cla: yes, approved, lgtm

#1229 🏃 update PR icon template to match CAPI
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1228 :seedling: Update RELEASE.md process for release branches
  RELEASE.md
Labels: size/M, cncf-cla: yes, approved, lgtm
