Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2022-07, with the labels that each got.

#1284 🐛 Fix logger arguments
  pkg/cloud/services/compute/instance_types.go
  pkg/cloud/services/compute/instance_types_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1283 ✨ Bump to CAPI v1.2.0-beta.1
  .golangci.yml
  Containerfile
  Dockerfile
  Makefile
  README.md
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controllers/openstackcluster_controller.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  netlify.toml
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
  versions.mk
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1296 ✨ Enable JSON Logging
  go.mod
  go.sum
  main.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#1294 🌱 only reconcile loadbalancer member if machine is control-plane
  controllers/openstackmachine_controller.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1295 🌱 bump to capi v1.2.0-rc.0
  Makefile
  api/v1alpha6/openstackmachinetemplate_webhook.go
  api/v1alpha6/openstackmachinetemplate_webhook_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
  test/e2e/data/e2e_conf.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#1297 🌱 Set ginkgo.timeout in our kubetest config
  test/e2e/data/kubetest/conformance-fast.yaml
  test/e2e/data/kubetest/conformance.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1302 🌱 Bump CAPI to v1.2.0
  Makefile
  cloudbuild-nightly.yaml
  cloudbuild.yaml
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#1304 e2e test: add more dump output
  test/e2e/shared/openstack.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1303 ✨ Add re-creation of bastion host on change
  api/v1alpha6/openstackcluster_webhook.go
  api/v1alpha6/openstackcluster_webhook_test.go
  controllers/openstackcluster_controller.go
  docs/book/src/clusteropenstack/configuration.md
  go.mod
  pkg/cloud/services/compute/instance.go
  pkg/utils/hash/hash.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1307 🐛 Update calico manifest for e2e testing
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
  test/e2e/data/cni/calico.yaml
Labels: cncf-cla: yes, approved, size/XL, lgtm

#1276 not assign floating ip when there are multiple controller nodes
  controllers/openstackmachine_controller.go
  docs/book/src/clusteropenstack/configuration.md
Labels: size/M, cncf-cla: yes, approved, lgtm

#1309 🌱 Ensure that python and pip is installed for e2e and conformance tests
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#1288 ✨ Conditions for OpenStackMachines
  api/v1alpha3/openstackmachine_types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/openstackmachine_types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1alpha5/openstackmachine_types.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha5/zz_generated.deepcopy.go
  api/v1alpha6/conditions_consts.go
  api/v1alpha6/openstackmachine_types.go
  api/v1alpha6/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  controllers/openstackmachine_controller.go
Labels: cncf-cla: yes, approved, size/L, lgtm
