Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2022-02, with the labels that each got.

#1125 ✨ Ensure trunk deletion
  hack/ci/cloud-init/controller.yaml.tpl
  pkg/cloud/services/networking/trunk.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1136 🐛Bump CAPI to v1.0.4
  Makefile
  go.mod
  go.sum
  metadata.yaml
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#1128 Add test for trunk feature
  test/e2e/shared/openstack.go
  test/e2e/suites/e2e/e2e_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1142 📖 Document external repositories referencing CAPO owners
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1141 manager.yaml: enable metrics endpoint
  config/manager/manager.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1123 🏃 OWNERS: satisfy the maintainers tool
  OWNERS
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1138 Avoid set failMessage when bastion creation failed
  controllers/openstackcluster_controller.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1152 Make hidekazuna emeritus
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1144 🏃 devstack: Allow empty private SSH key
  hack/ci/aws-project.sh
  hack/ci/create_devstack.sh
  hack/ci/gce-project.sh
  hack/ci/openstack.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#1156 🐛 containerfile: Bump Go version
  Containerfile
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test
