Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2022-09, with the labels that each got.

#1333 🌱 remove apricote from reviewers
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1330 update k8s to 1.25
  README.md
  test/e2e/data/e2e_conf.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1340 🐛 fix nilpointer during clusterctl move
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1335 update doc to make it more clear
  docs/book/src/clusteropenstack/configuration.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1338 doc: update calico location
  docs/book/src/topics/external-cloud-provider.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1343 🌱 Group Makefile targets
  Makefile
  common.mk
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#1318 ✨ Allow for omitting AZ from control plane nodes
  api/v1alpha3/conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/conversion_test.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/openstackcluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  controllers/openstackcluster_controller.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test
