Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2022-10, with the labels that each got.

#1352 ci: Pin to the yoga version of openstackclient
  hack/ci/create_devstack.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#1350 🐛 Don't require an InstanceSpec for DeleteInstance
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1342 🌱 Update golangci-lint (v1.46.2 -> v1.50.0), remove deprecated linters
  .golangci.yml
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
  pkg/cloud/services/loadbalancer/mock_loadbalancer/doc.go
  pkg/cloud/services/networking/mock_networking/doc.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#1354 🌱 Add the cluster templates back
  scripts/ci-test.sh
  templates/.gitignore
  templates/cluster-template-external-cloud-provider.yaml
  templates/cluster-template-without-lb.yaml
  templates/cluster-template.yaml
Labels: cncf-cla: yes, approved, size/XL, lgtm, ok-to-test

#1353 🐛 Don't require cinder when not using volumes
  pkg/clients/compute.go
  pkg/clients/image.go
  pkg/clients/loadbalancer.go
  pkg/clients/mock/compute.go
  pkg/clients/mock/doc.go
  pkg/clients/mock/image.go
  pkg/clients/mock/loadbalancer.go
  pkg/clients/mock/network.go
  pkg/clients/mock/volume.go
  pkg/clients/networking.go
  pkg/clients/volume.go
  pkg/cloud/services/compute/availabilityzone.go
  pkg/cloud/services/compute/client.go
  pkg/cloud/services/compute/client_mock.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/instance_types.go
  pkg/cloud/services/compute/instance_types_test.go
  pkg/cloud/services/compute/service.go
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
  pkg/cloud/services/loadbalancer/mock_loadbalancer/doc.go
  pkg/cloud/services/loadbalancer/service.go
  pkg/cloud/services/networking/floatingip_test.go
  pkg/cloud/services/networking/mock_networking/doc.go
  pkg/cloud/services/networking/port_test.go
  pkg/cloud/services/networking/service.go
  pkg/cloud/services/networking/trunk_test.go
  test/e2e/shared/openstack.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1357 🌱 Remove unnecessary mock import aliases
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
  pkg/cloud/services/networking/floatingip_test.go
  pkg/cloud/services/networking/port_test.go
  pkg/cloud/services/networking/trunk_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#1361 🌱 Bump CAPI to v1.2.4
  Makefile
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1364 🌱 CI: Clean openstack volumes
  hack/ci/create_devstack.sh
  hack/ci/openstack.sh
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#1281 switch version from float to int
  pkg/cloud/services/compute/instance_types.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, lifecycle/rotten

#1366 Fix accesIPv4 checking
  pkg/cloud/services/compute/instance.go
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test
