Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2022-12, with the labels that each got.

#1408 🐛 Update Ubuntu, CirrOS & Amphora image
  docs/book/src/development/development.md
  hack/ci/cloud-init/controller.yaml.tpl
  test/e2e/data/e2e_conf.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1405 🌱Release 0.7 patches
  metadata.yaml
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1406 ✨ Bump CAPI to v1.3.0
  Containerfile
  Dockerfile
  Makefile
  RELEASE.md
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  controllers/openstackcluster_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  main.go
  netlify.toml
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/kubetest/conformance-fast-ginkgo-v2.yaml
  test/e2e/data/kubetest/conformance-fast.yaml
  test/e2e/data/kubetest/conformance-ginkgo-v2.yaml
  test/e2e/data/kubetest/conformance.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/shared/common.go
  test/e2e/shared/exec.go
  test/e2e/shared/openstack.go
  test/e2e/shared/openstack_test.go
  test/e2e/shared/suite.go
  test/e2e/suites/conformance/conformance_suite_test.go
  test/e2e/suites/conformance/conformance_test.go
  test/e2e/suites/e2e/clusterctl_upgrade_test.go
  test/e2e/suites/e2e/e2e_suite_test.go
  test/e2e/suites/e2e/e2e_test.go
  versions.mk
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1412 🌱 Remove It block from clusterctl upgrade
  test/e2e/suites/e2e/clusterctl_upgrade_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1417 🌱 e2e: Change logging to avoid use of By
  test/e2e/shared/cluster.go
  test/e2e/shared/common.go
  test/e2e/shared/openstack.go
  test/e2e/shared/suite.go
  test/e2e/suites/e2e/clusterctl_upgrade_test.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1418 :book: Fix spelling errors on docs
  docs/book/src/clusteropenstack/configuration.md
  docs/book/src/development/ci.md
  docs/book/src/topics/mover.md
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1420 🌱 Backport E2E test fixes
  test/e2e/shared/cluster.go
  test/e2e/shared/common.go
  test/e2e/shared/openstack.go
  test/e2e/shared/suite.go
  test/e2e/suites/e2e/clusterctl_upgrade_test.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1421 ✨Add lentzi90 to reviewers
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1424 🌱Bump CAPI to v1.3.1
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
  test/e2e/suites/e2e/clusterctl_upgrade_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1427 🐛 uplift x/net to 0.4.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test
