Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2023-05, with the labels that each got.

#1534 Update linter to v1.52.2
  api/v1alpha3/conversion.go
  api/v1alpha4/conversion.go
  api/v1alpha5/conversion.go
  api/v1alpha7/openstackmachinetemplate_webhook.go
  controllers/openstackmachine_controller.go
  hack/tools/Makefile
  pkg/clients/compute.go
  pkg/clients/image.go
  pkg/clients/volume.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/scope/mock.go
  test/e2e/suites/e2e/e2e_suite_test.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1527 ⚠️ Remove v1alpha3 and v1alpha4
  .golangci.yml
  Makefile
  PROJECT
  README.md
  api/v1alpha3/conversion.go
  api/v1alpha3/conversion_test.go
  api/v1alpha3/doc.go
  api/v1alpha3/groupversion_info.go
  api/v1alpha3/openstackcluster_conversion.go
  api/v1alpha3/openstackcluster_types.go
  api/v1alpha3/openstackmachine_types.go
  api/v1alpha3/openstackmachinetemplate_types.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/conversion.go
  api/v1alpha4/conversion_test.go
  api/v1alpha4/doc.go
  api/v1alpha4/groupversion_info.go
  api/v1alpha4/identity_types.go
  api/v1alpha4/openstackcluster_conversion.go
  api/v1alpha4/openstackcluster_types.go
  api/v1alpha4/openstackclustertemplate_types.go
  api/v1alpha4/openstackmachine_types.go
  api/v1alpha4/openstackmachinetemplate_types.go
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  config/crd/kustomization.yaml
  go.mod
  main.go
  metadata.yaml
  pkg/cloud/services/compute/instance_test.go
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1537 Add lentzi90 to cluster-api-openstack-maintainers
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1538 [release-0.7] Add lentzi90 to cluster-api-openstack-maintainers
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1518 ⚠️ Remove Networks
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackmachine_types.go
  api/v1alpha7/types.go
  api/v1alpha7/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  docs/book/src/topics/crd-changes/v1alpha6-to-v1alpha7.md
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/instance_types.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1536 Update external approvers
  OWNERS
  OWNERS_ALIASES
Labels: size/S, cncf-cla: yes, approved, lgtm

#1543 Fix OWNERS_ALIASES syntax error
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm

#1542 Use dl.k8s.io instead of kubernetes-release bucket
  hack/ensure-kubectl.sh
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1516 ⚠️ Remove PortOpts.SecurityGroups
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/types.go
  api/v1alpha7/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  docs/book/src/topics/crd-changes/v1alpha6-to-v1alpha7.md
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1546 🌱 Reduce the Bastion status to only fields which are used
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackcluster_types.go
  api/v1alpha7/openstackcluster_webhook_test.go
  api/v1alpha7/types.go
  api/v1alpha7/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  controllers/openstackcluster_controller.go
  go.mod
  pkg/cloud/services/compute/instance_types.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#1550 🌱Remove PortOpts from Network
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/types.go
  api/v1alpha7/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#1555 🌱Remove unused fields from ExternalNetwork
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackcluster_types.go
  api/v1alpha7/types.go
  api/v1alpha7/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
  pkg/cloud/services/networking/floatingip_test.go
  pkg/cloud/services/networking/network.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1557 ⚠️ Replace SecurityGroupParam with SecurityGroupFilter
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackmachine_types.go
  api/v1alpha7/types.go
  api/v1alpha7/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  controllers/openstackmachine_controller_test.go
  docs/book/src/topics/crd-changes/v1alpha6-to-v1alpha7.md
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/instance_types.go
  pkg/cloud/services/networking/port_test.go
  pkg/cloud/services/networking/securitygroups.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#1559 ⚠️ Replace SubnetParam with SubnetFilter
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/types.go
  api/v1alpha7/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  docs/book/src/topics/crd-changes/v1alpha6-to-v1alpha7.md
  pkg/cloud/services/networking/router.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1562 :seedling: bump docker distribution to 2.8.2+incompatible
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1563 ⚠️Remove last uses of TenantID and pagination filters
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/filter_convert.go
  api/v1alpha7/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  docs/book/src/topics/crd-changes/v1alpha6-to-v1alpha7.md
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
  pkg/cloud/services/networking/securitygroups.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1551 🌱 Set provider ID through kubelet in ubuntu templates
  kustomize/v1alpha7/default/cluster-template.yaml
  kustomize/v1alpha7/external-cloud-provider/kustomization.yaml
  kustomize/v1alpha7/external-cloud-provider/patch-ccm.yaml
  kustomize/v1alpha7/flatcar/patch-flatcar.yaml
  templates/cluster-template-external-cloud-provider-flatcar.yaml
  templates/cluster-template-intree-cloud-provider.yaml
  templates/cluster-template-without-lb.yaml
  templates/cluster-template.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#1560 :warning: Transform `Profile` into an interface
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/types.go
  api/v1alpha7/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  docs/book/src/topics/crd-changes/v1alpha6-to-v1alpha7.md
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#1568 🌱 E2e: Bump clusterctl upgrade to start from v0.7.2
  Makefile
  test/e2e/data/e2e_conf.yaml
  test/e2e/suites/e2e/clusterctl_upgrade_test.go
Labels: size/S, cncf-cla: yes, approved, lgtm
