Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2023-04, with the labels that each got.

#1521 :seedling: pull cluster-api@v1.4.1
  .golangci.yml
  api/v1alpha6/openstackmachine_types.go
  api/v1alpha7/openstackmachine_types.go
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  controllers/openstackmachine_controller_test.go
  go.mod
  go.sum
  hack/ci/cloud-init/common.yaml.tpl
  hack/ci/cloud-init/controller.yaml.tpl
  hack/ci/cloud-init/worker.yaml.tpl
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/cloud/services/compute/instance_test.go
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/shared/common.go
  test/e2e/shared/openstack.go
  test/e2e/suites/conformance/conformance_test.go
  test/e2e/suites/e2e/clusterctl_upgrade_test.go
  test/e2e/suites/e2e/e2e_test.go
  test/e2e/suites/e2e/remediations_test.go
  test/helpers/external/cluster.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#1522 :warning: flatcar: make external-cloud-provider-flatcar the default one
  Makefile
  RELEASE.md
  docs/book/src/clusteropenstack/configuration.md
  kustomize/v1alpha7/flatcar/kustomization.yaml
  kustomize/v1alpha7/flatcar/patch-flatcar.yaml
  templates/cluster-template-flatcar.yaml
  test/e2e/data/kustomize/external-cloud-provider-flatcar/kustomization.yaml
  test/e2e/data/kustomize/flatcar/ccm.yaml
  test/e2e/data/kustomize/flatcar/kustomization.yaml
  test/e2e/shared/defaults.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1525 🌱 bump docker to 20.10.24+incompatible
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1524 :seedling: ci: bump flatcar to latest major stable
  hack/ci/cloud-init/controller.yaml.tpl
  test/e2e/data/e2e_conf.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1519 ✨Infer port network from subnet
  controllers/openstackcluster_controller.go
  docs/book/src/clusteropenstack/configuration.md
  go.mod
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#1526 ✨Infer port network from subnet
  controllers/openstackcluster_controller.go
  docs/book/src/clusteropenstack/configuration.md
  go.mod
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#1481 ✨ Support propagate uplink status
  api/v1alpha4/conversion_test.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/types.go
  api/v1alpha7/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1381 🐛 Improve `env.rc` and `create_cloud_conf.sh` templates
  templates/create_cloud_conf.sh
  templates/env.rc
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#1530 🐛 Patch: Backport Provider to v1alpha6
  api/v1alpha5/conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/types.go
  api/v1alpha6/zz_generated.conversion.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1529 ✨ Backport Provider to release-0.7
  api/v1alpha3/conversion_test.go
  api/v1alpha4/conversion_test.go
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/utils/errors/errors.go
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1531 🌱 Remove creation of 2 Events for the same event
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: cncf-cla: yes, approved, size/XS, lgtm
