Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2023-12, with the labels that each got.

#1764 📖 Fix network-related docs for API v1alpha7
  docs/book/src/clusteropenstack/configuration.md
  versions.mk
Labels: cncf-cla: yes, approved, size/L, lgtm

#1770 🐛 Verify success of parsing OpenStack cloud cacert
  pkg/scope/provider.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1775 🌱 Bump version artifacts for release-0.9
  metadata.yaml
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1785 🐛 Don't apply worker SG to control plane machines
  controllers/openstackmachine_controller.go
  controllers/openstackmachine_controller_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1793 Remove Tobias and Sean as maintainer
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1798 🌱 Update links in release docs
  RELEASE.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1766 🌱 Make it possible to use a pre-created volume type in e2e tests
  hack/ci/cloud-init/controller.yaml.tpl
  test/e2e/suites/e2e/e2e_suite_test.go
  test/e2e/suites/e2e/e2e_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1803 :bug: Fix potential panic during instance create
  pkg/cloud/services/compute/instance.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test
