Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2023-06, with the labels that each got.

#1572 🐛 Always filter cluster subnets by cluster network ID
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  pkg/cloud/services/networking/network.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1573 🐛 Always filter cluster subnets by cluster network ID
  controllers/openstackcluster_controller.go
  pkg/cloud/services/networking/network.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#1575 ⚠️ Remove ProjectID from PortOpts
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  docs/book/src/topics/crd-changes/v1alpha6-to-v1alpha7.md
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#1571 🌱 Bump Kubernetes version used in e2e tests
  .gitignore
  hack/ci/cloud-init/controller.yaml.tpl
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/kustomize/common-patches/ccm/ccm.yaml
  test/e2e/data/kustomize/common-patches/ccm/kustomization.yaml
  test/e2e/data/kustomize/common-patches/containerd/containerd-kcp.yaml
  test/e2e/data/kustomize/common-patches/containerd/containerd-kct.yaml
  test/e2e/data/kustomize/default/kustomization.yaml
  test/e2e/data/kustomize/flatcar/ccm.yaml
  test/e2e/data/kustomize/flatcar/kustomization.yaml
  test/e2e/data/kustomize/v1alpha5/kustomization.yaml
  test/e2e/data/kustomize/v1alpha6/kustomization.yaml
  test/e2e/data/kustomize/without-lb/ccm.yaml
  test/e2e/data/kustomize/without-lb/kustomization.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#1579 🐛 Fix deadlock
  controllers/openstackcluster_controller.go
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#1583 🐛 Fix Deletion Deadlock Part Deux
  controllers/openstackcluster_controller.go
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#1584 🌱 dependencies: Bump Go stdlib
  go.mod
  go.sum
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1585 🌱 Replace github.com/pkg/errors
  api/v1alpha7/openstackmachine_webhook.go
  controllers/openstackcluster_controller.go
  go.mod
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#1592 :sparkles: Add additional sec group rule for additionalPorts of LB
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/networking/securitygroups_rules.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1590 ✨ Allowing update of OpenstackCluster API server fixed IP
  api/v1alpha7/openstackcluster_webhook.go
  api/v1alpha7/openstackcluster_webhook_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1581 🌱 E2e: Implement LogCollector interface
  scripts/ci-e2e.sh
  test/e2e/shared/common.go
  test/e2e/shared/suite.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1594 🌱 E2e: Bump the tested Kubernetes versions
  README.md
  hack/ci/cloud-init/controller.yaml.tpl
  test/e2e/data/e2e_conf.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1595 🌱 E2e: Unify machine log collection
  test/e2e/shared/common.go
  test/e2e/shared/openstack.go
  test/e2e/shared/suite.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1577 ⚠️ Update NetworkStatus ready for dual stack
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackcluster_types.go
  api/v1alpha7/types.go
  api/v1alpha7/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller_test.go
  docs/book/src/topics/crd-changes/v1alpha6-to-v1alpha7.md
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
Labels: cncf-cla: yes, approved, size/XL, lgtm
