Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2023-02, with the labels that each got.

#1380 Add e2e remediation tests
  Makefile
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/kustomize/kcp-remediation/kustomization.yaml
  test/e2e/data/kustomize/kcp-remediation/mhc.yaml
  test/e2e/data/kustomize/md-remediation/kustomization.yaml
  test/e2e/data/kustomize/md-remediation/md.yaml
  test/e2e/data/kustomize/md-remediation/mhc.yaml
  test/e2e/shared/defaults.go
  test/e2e/suites/e2e/mhc_remediations_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1430 🐛 Fix Tilt by adding CAPO label in tilt-provider.json
  tilt-provider.json
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1457 ✨ Add Tags to API-Loadbalancer resources
  api/v1alpha3/conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/conversion_test.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/types.go
  api/v1alpha6/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#1464 🐛 Return from reconciler after adding finalizer
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1467 📖 Add documentation about --ca-cert flag
  docs/book/src/clusteropenstack/configuration.md
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#1463 🌱 Bump gophercloud to v1.2.0
  go.mod
  go.sum
Labels: size/S, cncf-cla: yes, approved, lgtm

#1470 Download golangci-lint instead of building it
  hack/boilerplate/boilerplate.py
  hack/tools/Makefile
  hack/tools/ensure-golangci-lint.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1473 Fix boilerplate linter
  hack/boilerplate/boilerplate.py
  hack/verify-boilerplate.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#1471 Remove the resource and machine tickers from e2e tests
  test/e2e/shared/common.go
  test/e2e/shared/context.go
  test/e2e/shared/openstack.go
  test/e2e/shared/suite.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1474 Fix "internal ip doesn't exist (yet)" in e2e logs
  test/e2e/shared/common.go
  test/e2e/shared/openstack.go
  test/e2e/suites/e2e/e2e_test.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#1482 🐛 uplift golang and x/net
  Containerfile
  Dockerfile
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  versions.mk
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1479 :bug: Fix Provisioning to Unavailable AZs
  api/v1alpha6/openstackcluster_webhook.go
  api/v1alpha6/openstackcluster_webhook_test.go
  pkg/cloud/services/compute/availabilityzone.go
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1489 🐛 Switch to "4" instead of "ipip" for rules
  pkg/cloud/services/networking/securitygroups_rules.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1492 fix: fix typo of worker rules and controller rules
  pkg/cloud/services/networking/securitygroups.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1452 ✨ Support value specs for Ports
  api/v1alpha4/conversion_test.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/types.go
  api/v1alpha6/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm
