Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2023-01, with the labels that each got.

#1423 ✨Add lentzi90 to reviewers
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1432 🌱Be more robust when checking gophercloud errors in IsNotFound
  pkg/utils/errors/errors.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#1443 🌱Add log to provide more info in case error happen
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1445 🐛 fix nil-pointer in initial reconciliation loop with empty status field
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#1441 🌱 E2e: Use plain ubuntu cloud image
  hack/ci/cloud-init/controller.yaml.tpl
  kustomize/v1alpha5/external-cloud-provider/patch-ccm.yaml
  kustomize/v1alpha6/external-cloud-provider/patch-ccm.yaml
  templates/cluster-template-external-cloud-provider.yaml
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/kustomize/common-patches/containerd-kcp.yaml
  test/e2e/data/kustomize/common-patches/containerd-kct.yaml
  test/e2e/data/kustomize/common-patches/kustomization.yaml
  test/e2e/data/kustomize/external-cloud-provider/kustomization.yaml
  test/e2e/data/kustomize/external-cloud-provider/patch-ccm-cloud-config.yaml
  test/e2e/data/kustomize/external-cloud-provider/patch-ccm.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#1456 🌱 Use newer containerd in e2e tests
  test/e2e/data/kustomize/common-patches/containerd-kcp.yaml
  test/e2e/data/kustomize/common-patches/containerd-kct.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1440 ✨ Add ca-cert flag to supply a default ca certificate for each requests
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  main.go
  pkg/cloud/services/provider/provider.go
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1454 📖 fix path for taggin and serverMetadata in OpenstackMachineTemplates
  docs/book/src/clusteropenstack/configuration.md
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#1461 ✨ add explicit securitycontext to controller
  config/manager/manager.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1451 check flavor and reject CPUs less than 2
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/clients/compute.go
  pkg/clients/mock/compute.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1460 🌱 Bump ginkgo to v2.7.0 and sync with hack/tools
  api/v1alpha6/openstackmachinetemplate_webhook_test.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/M, cncf-cla: yes, approved, lgtm

#1236 Envtest mocks
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  controllers/openstackmachine_controller.go
  main.go
  pkg/clients/compute.go
  pkg/clients/image.go
  pkg/clients/loadbalancer.go
  pkg/clients/networking.go
  pkg/clients/volume.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/service.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
  pkg/cloud/services/loadbalancer/service.go
  pkg/cloud/services/networking/floatingip.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/networking/service.go
  pkg/scope/mock.go
  pkg/scope/provider.go
  pkg/scope/scope.go
  test/e2e/shared/openstack.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#1428 🌱 Add e2e self hosted test
  test/e2e/data/e2e_conf.yaml
  test/e2e/suites/e2e/self_hosted_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm
