Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2023-03, with the labels that each got.

#1498 🐛 fix: allow using multiattach volume types
  README.md
  pkg/clients/compute.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1500 📖 Add documentation for creating local test environments
  docs/book/src/development/development.md
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1503 :book: docs/configuration: add Flatcar to OS section
  docs/book/src/clusteropenstack/configuration.md
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#1509 🌱 Add fuzzy conversion tests for v1alpha6
  api/v1alpha6/conversion_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1504 ⚠️Remove OpenStackMachineSpec.Subnet
  api/v1alpha3/conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/conversion_test.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  controllers/openstackmachine_controller.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_types.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1501 ✨Add Octavia OVN Provider Support
  api/v1alpha3/conversion_test.go
  api/v1alpha4/conversion_test.go
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/utils/errors/errors.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#1511 🌱 Un-pointer PortOpts.SecurityGroups
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1alpha5/types.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha5/zz_generated.deepcopy.go
  api/v1alpha6/types.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha6/zz_generated.deepcopy.go
  api/v1alpha7/types.go
  api/v1alpha7/zz_generated.deepcopy.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1517 Restore APIServerLoadBalancer.Provider on up-conversion
  api/v1alpha6/conversion.go
  api/v1alpha6/conversion_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1370 :sparkles: Add RouterName for use existing router
  api/v1alpha3/conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/conversion_test.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/filter_convert.go
  api/v1alpha7/openstackcluster_types.go
  api/v1alpha7/types.go
  api/v1alpha7/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  docs/book/src/clusteropenstack/configuration.md
  pkg/cloud/services/networking/router.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test
