Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2023-08, with the labels that each got.

#1625 🌱 Simplify types of Instance.SecurityGroup and Instance.Networks
  api/v1alpha5/types.go
  api/v1alpha5/zz_generated.deepcopy.go
  api/v1alpha6/types.go
  api/v1alpha6/zz_generated.deepcopy.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1600 ✨ Update to CAPI 1.5
  api/v1alpha7/openstackcluster_webhook.go
  api/v1alpha7/openstackcluster_webhook_test.go
  api/v1alpha7/openstackclustertemplate_webhook.go
  api/v1alpha7/openstackmachine_webhook.go
  api/v1alpha7/openstackmachinetemplate_webhook.go
  api/v1alpha7/openstackmachinetemplate_webhook_test.go
  api/v1alpha7/webhooks.go
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  go.mod
  go.sum
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/trunk.go
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/shared/common.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1614 🌱 chore: use capo cluster agent for API requests
  pkg/scope/provider.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1633 ✨ Add support to IPv6 in Machine's status
  pkg/cloud/services/compute/instance_types.go
  pkg/cloud/services/compute/instance_types_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1641 ✨ Add `--version` flag
  main.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1621 :seedling: Migrating /pkg/cloud/services/loadbalancer/loadbalancer.go and /controllers/openstackmachine_controller.go to structured logging
  controllers/openstackmachine_controller.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#1630 🌱Migrate controllers/openstackcluster_controller.go to structured logging
  controllers/openstackcluster_controller.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1642 🌱Remove APIServerLoadBalancer.Provider Up Conversion
  api/v1alpha6/conversion.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1646 🐛 Fix application credential support in env.rc
  templates/env.rc
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#1624 🌱 Migrate pkg/cloud/services/networking/network.go and router.go to structured logging
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/router.go
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#1638 📖 Fix APIVersion to use existing router with OpenStackCluster
  docs/book/src/clusteropenstack/configuration.md
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1635 🌱 Update verbosity levels in instance.go
  pkg/cloud/services/compute/instance.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1648 :bug: Fix Port Leaks
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test
