Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2024-09, with the labels that each got.

#2154 🌱 Bump CAPI to v1.8.1
  Makefile
  api_violations.report
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackservers.yaml
  config/manager/manager.yaml
  go.mod
  go.sum
  hack/boilerplate/boilerplate.py
  hack/codegen/go.mod
  hack/codegen/go.sum
  hack/codegen/go.work
  hack/codegen/go.work.sum
  hack/codegen/openapi/zz_generated.openapi.go
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
  main_test.go
  orc/api_violations.report
  orc/go.mod
  orc/go.sum
  orc/hack/codegen/openapi/zz_generated.openapi.go
  pkg/generated/applyconfiguration/internal/internal.go
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/suites/e2e/clusterctl_upgrade_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#2175 🌱 Allow running CAPO and ORC tests separately
  Makefile
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2163 ✨ support server group and scheduler hint additional properties
  api/v1alpha1/openstackserver_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha6/openstackmachine_conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackmachine_conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/openstackmachine_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackservers.yaml
  controllers/openstackmachine_controller.go
  controllers/openstackserver_controller.go
  docs/book/src/api/v1alpha1/api.md
  docs/book/src/api/v1beta1/api.md
  hack/codegen/openapi/zz_generated.openapi.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/instance_types.go
  pkg/generated/applyconfiguration/api/v1alpha1/openstackserverspec.go
  pkg/generated/applyconfiguration/api/v1beta1/openstackmachinespec.go
  pkg/generated/applyconfiguration/api/v1beta1/schedulerhintadditionalproperty.go
  pkg/generated/applyconfiguration/api/v1beta1/schedulerhintadditionalvalue.go
  pkg/generated/applyconfiguration/internal/internal.go
  pkg/generated/applyconfiguration/utils.go
  test/e2e/suites/apivalidations/openstackmachine_test.go
Labels: cncf-cla: yes, approved, size/XL, lgtm, ok-to-test

#2180 🐛 Image controller: don't attempt upload when adopting
  internal/controllers/image/reconcile.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2178 🐛 Ensure SSA patch can't accidentally create a new object
  internal/controllers/image/reconcile.go
  internal/controllers/image/status.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2174 ⚠️ Convert APIServerPort to uint16
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/openstackcluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  docs/book/src/api/v1beta1/api.md
  hack/codegen/openapi/zz_generated.openapi.go
  pkg/generated/applyconfiguration/api/v1beta1/openstackclusterspec.go
  pkg/utils/optional/conversion.go
  pkg/utils/optional/types.go
  pkg/webhooks/openstackcluster_webhook_test.go
  test/e2e/suites/apivalidations/openstackcluster_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm
