Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2024-12, with the labels that each got.

#2296 📖 Add docs about microversions
  docs/book/src/clusteropenstack/configuration.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#2295 🌱 E2E: Use CAPI production images and skip cert-manager pre-pull
  Makefile
  test/e2e/data/e2e_conf.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#2294 🌱 Fix conformance suite
  .gitignore
  Makefile
  test/e2e/data/e2e_conf.yaml
  test/e2e/suites/conformance/conformance_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#2291 🐛 Fix deletion of cluster when bastion image missing
  controllers/openstackcluster_controller.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2307 🐛 ci/devstack: host tuning
  hack/ci/cloud-init/controller.yaml.tpl
  hack/ci/cloud-init/worker.yaml.tpl
Labels: size/S, cncf-cla: yes, approved, lgtm

#2322 🌱 [release-0.11] Bump CAPI to v1.8.6
  Makefile
  go.mod
  go.sum
  hack/codegen/go.mod
  hack/codegen/go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/data/e2e_conf.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#2316 🌱 CI: Increase IOPS for the devstack disks
  hack/ci/gce-project.sh
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2319 🌱 devstack: build OVN from source
  hack/ci/cloud-init/controller.yaml.tpl
  hack/ci/cloud-init/worker.yaml.tpl
Labels: size/S, cncf-cla: yes, approved, lgtm

#2340 :seedling: Update golang.org/x/net to v0.33.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/S, cncf-cla: yes, approved, lgtm

#2342 🌱 [release-0.11] update CAPI to v1.8.8
  Makefile
  go.mod
  go.sum
  hack/codegen/go.mod
  hack/codegen/go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/data/e2e_conf.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm
