Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2024-02, with the labels that each got.

#1849 🌱 Decrease number of machines in e2e tests
  test/e2e/suites/e2e/e2e_test.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#1857 Migrate Dockerfile to use golang 1.21 to match go.mod in project
  Dockerfile
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1853 🐛Fix a stacktrace in LB logic by removing listener name from an error message when not set
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1858 :seedling: test: bump Flatcar version
  hack/ci/cloud-init/controller.yaml.tpl
  test/e2e/data/e2e_conf.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1865 fix: fix the block device type name in doc
  docs/book/src/topics/crd-changes/v1alpha6-to-v1alpha7.md
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1842 🐛 api: openstackcluster.status default to false
  api/v1alpha8/openstackcluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1864 🐛 Adds Kind to ipaddress pool name index
  controllers/openstackfloatingippool_controller.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1867 :sparkles: add TLS configuration flags
  main.go
  main_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#1870 OpenstackFloatingIPPool: Adds popped ip to claimedIPs #1869
  controllers/openstackfloatingippool_controller.go
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#1866 🐛 Prevent the bastion to be removed before it's been disabled
  api/v1alpha8/openstackcluster_types.go
  api/v1alpha8/openstackcluster_webhook.go
  api/v1alpha8/openstackcluster_webhook_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  controllers/openstackcluster_controller.go
  docs/book/src/clusteropenstack/configuration.md
Labels: size/M, cncf-cla: yes, approved, lgtm

#1877 ✨ Bump Go to 1.22.0
  Dockerfile
  go.mod
  hack/tools/go.mod
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1883 🐛 Ignore 'OS_*' environment variables
  pkg/scope/provider.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1888 ⚠️ Stop serving v1alpha5
  api/v1alpha5/openstackcluster_types.go
  api/v1alpha5/openstackclustertemplate_types.go
  api/v1alpha5/openstackmachine_types.go
  api/v1alpha5/openstackmachinetemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1889 🌱 Fix doc references to NodeCIDR in v1alpha8
  api/v1alpha8/openstackcluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#1893 🐛 e2e: stop testing upgrades from v1alpha5 (v0.6)
  Makefile
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/kustomize/v1alpha5/bastion.yaml
  test/e2e/data/kustomize/v1alpha5/kustomization.yaml
  test/e2e/shared/defaults.go
  test/e2e/suites/e2e/clusterctl_upgrade_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1895 🌱 Enforce restricted pod security standards
  config/default/namespace.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1862 ✨ Adds MaxIPs to OpenstackFloatingIPPool
  api/v1alpha1/conditions_consts.go
  api/v1alpha1/openstackfloatingippool_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackfloatingippools.yaml
  controllers/openstackfloatingippool_controller.go
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#1894 🌱 E2E: Add clusterctl upgrade test for v0.9 -> main
  test/e2e/data/e2e_conf.yaml
  test/e2e/suites/e2e/clusterctl_upgrade_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1738 🐛 loadbalancer: resolve ControlPlaneEndpoint.Host when needed
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1826 ✨ AllNodes security groups API
  api/v1alpha5/conversion.go
  api/v1alpha5/conversion_test.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/conversion.go
  api/v1alpha7/conversion_test.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1alpha8/conversion.go
  api/v1alpha8/openstackcluster_types.go
  api/v1alpha8/openstackcluster_webhook.go
  api/v1alpha8/openstackcluster_webhook_test.go
  api/v1alpha8/types.go
  api/v1alpha8/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  controllers/openstackmachine_controller_test.go
  docs/book/src/clusteropenstack/configuration.md
  docs/book/src/topics/crd-changes/v1alpha7-to-v1alpha8.md
  kustomize/v1alpha8/default/cluster-template.yaml
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/networking/securitygroups_rules.go
  pkg/cloud/services/networking/securitygroups_test.go
  templates/cluster-template-flatcar-sysext.yaml
  templates/cluster-template-flatcar.yaml
  templates/cluster-template-without-lb.yaml
  templates/cluster-template.yaml
  templates/clusterclass-dev-test.yaml
  test/e2e/shared/openstack.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1898 Add emilienm to CAPO reviewers
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1836 ✨ Modify OpenStackCluster.Spec.Network API
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  docs/book/src/topics/crd-changes/v1alpha7-to-v1alpha8.md
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/network_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1900 🌱 Deprecate v1alpha6
  api/v1alpha6/openstackcluster_types.go
  api/v1alpha6/openstackclustertemplate_types.go
  api/v1alpha6/openstackmachine_types.go
  api/v1alpha6/openstackmachinetemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#1822 🐛 e2e: bastion tests
  hack/ci/cloud-init/controller.yaml.tpl
  test/e2e/data/e2e_conf.yaml
  test/e2e/shared/defaults.go
  test/e2e/shared/openstack.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1903 🐛 Remove `IdentityRef.Kind`
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1alpha8/identity_types.go
  api/v1alpha8/openstackcluster_webhook.go
  api/v1alpha8/openstackcluster_webhook_test.go
  api/v1alpha8/openstackclustertemplate_webhook.go
  api/v1alpha8/openstackmachine_webhook.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  docs/book/src/topics/crd-changes/v1alpha7-to-v1alpha8.md
  kustomize/v1alpha8/default/cluster-template.yaml
  templates/cluster-template-flatcar-sysext.yaml
  templates/cluster-template-flatcar.yaml
  templates/cluster-template-without-lb.yaml
  templates/cluster-template.yaml
  templates/clusterclass-dev-test.yaml
  test/e2e/data/kustomize/k8s-upgrade/upgrade-from-template.yaml
  test/e2e/data/kustomize/k8s-upgrade/upgrade-to-template.yaml
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1788 ✨ Re-work ports management
  api/v1alpha5/conversion_test.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1alpha8/openstackmachine_types.go
  api/v1alpha8/types.go
  api/v1alpha8/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  controllers/openstackmachine_controller.go
  controllers/openstackmachine_controller_test.go
  controllers/suite_test.go
  pkg/cloud/services/compute/dependent_resources.go
  pkg/cloud/services/compute/dependent_resources_test.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/referenced_resources.go
  pkg/cloud/services/compute/referenced_resources_test.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
  pkg/cloud/services/networking/securitygroups.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1847 ✨ Add support to set `allocation_pools` for subnet
  api/v1alpha6/conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha7/conversion_test.go
  api/v1alpha8/types.go
  api/v1alpha8/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  docs/book/src/topics/crd-changes/v1alpha7-to-v1alpha8.md
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/network_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1911 🌱 Enhancements to how controller-gen is invoked
  Makefile
Labels: size/S, cncf-cla: yes, approved, lgtm

#1904 🌱 Reduce cyclomatic complexity of ReconcileLoadBalancer
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#1913 🐛 Remove logger from scope
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  controllers/openstackfloatingippool_controller.go
  controllers/openstackmachine_controller.go
  controllers/suite_test.go
  pkg/cloud/services/compute/dependent_resources.go
  pkg/cloud/services/compute/dependent_resources_test.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/instance_types_test.go
  pkg/cloud/services/compute/referenced_resources.go
  pkg/cloud/services/compute/referenced_resources_test.go
  pkg/cloud/services/compute/servergroup_test.go
  pkg/cloud/services/compute/service.go
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
  pkg/cloud/services/loadbalancer/service.go
  pkg/cloud/services/networking/network_test.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
  pkg/cloud/services/networking/securitygroups_test.go
  pkg/cloud/services/networking/service.go
  pkg/scope/mock.go
  pkg/scope/provider.go
  pkg/scope/scope.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1905 🌱 Reduce cyclomatic complexity of reconcileNetworkComponents
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1899 🐛 api/additionalPorts: don't create UDP rules
  pkg/cloud/services/networking/securitygroups_rules.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1914 ⚠️ API cleanup of PortOpts
  .golangci.yml
  Makefile
  api/v1alpha5/conversion.go
  api/v1alpha5/types.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/types.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/conversion.go
  api/v1alpha7/conversion_test.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/conversion.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  docs/book/src/api/v1beta1/api.md
  docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
  pkg/utils/optional/conversion.go
  pkg/utils/optional/types.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1915 ⚠️Move CloudName into IdentityRef and make cluster IdentityRef required
  api/v1alpha5/conversion.go
  api/v1alpha5/conversion_test.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/identity_types.go
  api/v1beta1/openstackcluster_types.go
  api/v1beta1/openstackcluster_webhook.go
  api/v1beta1/openstackcluster_webhook_test.go
  api/v1beta1/openstackmachine_types.go
  api/v1beta1/openstackmachine_webhook.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  controllers/openstackmachine_controller_test.go
  docs/book/src/api/v1beta1/api.md
  docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md
  kustomize/v1beta1/default/cluster-template.yaml
  pkg/scope/provider.go
  templates/cluster-template-flatcar-sysext.yaml
  templates/cluster-template-flatcar.yaml
  templates/cluster-template-without-lb.yaml
  templates/cluster-template.yaml
  templates/clusterclass-dev-test.yaml
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/XL, lgtm
