Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2024-08, with the labels that each got.

#2141 :seedling: E2E: Add subports to trunked port to test subports deletion
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#2151 🌱 netlify: Fix go version
  netlify.toml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2152 test: bump Flatcar Stable version
  hack/ci/cloud-init/controller.yaml.tpl
  test/e2e/data/e2e_conf.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2153 Copy InstanceID from OpenStackServer to OpenStackMachine
  controllers/openstackmachine_controller.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#2159 🐛 port: don't add any SGs when port security is disabled
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
  pkg/webhooks/openstackmachine_webhook.go
  pkg/webhooks/openstackserver_webhook.go
  test/e2e/suites/apivalidations/openstackmachine_test.go
  test/e2e/suites/apivalidations/openstackserver_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#2160 🌱 Dependency update
  go.mod
  go.sum
  hack/codegen/go.work.sum
  hack/tools/go.mod
  hack/tools/go.sum
  orc/go.mod
  orc/go.sum
  orc/hack/codegen/go.work.sum
Labels: cncf-cla: yes, approved, size/XL, lgtm

#2162 CI: update OpenStack to 2024.1 (Caracal)
  hack/ci/create_devstack.sh
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2164 :seedling: Backport #2081 and #2141 to release-0.9
  pkg/clients/mock/network.go
  pkg/clients/networking.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/networking/port_test.go
  pkg/cloud/services/networking/trunk.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#2165 :seedling: Backport #2081 and #2141 to release-0.10
  controllers/openstackmachine_controller_test.go
  pkg/clients/mock/network.go
  pkg/clients/networking.go
  pkg/cloud/services/networking/trunk.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#2167 openstackserver: create before delete if adoption fields are empty
  controllers/openstackcluster_controller.go
  controllers/openstackserver_controller.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#2168 :book: docs/configuration: fix security groups example
  docs/book/src/clusteropenstack/configuration.md
Labels: cncf-cla: yes, approved, size/XS, lgtm
