Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2024-07, with the labels that each got.

#2107 🌱 Upgrade Gophercloud to v2
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  controllers/openstackmachine_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  pkg/clients/compute.go
  pkg/clients/image.go
  pkg/clients/loadbalancer.go
  pkg/clients/mock/compute.go
  pkg/clients/mock/image.go
  pkg/clients/mock/loadbalancer.go
  pkg/clients/mock/network.go
  pkg/clients/mock/volume.go
  pkg/clients/networking.go
  pkg/clients/volume.go
  pkg/cloud/services/compute/availabilityzone.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/instance_types.go
  pkg/cloud/services/compute/instance_types_test.go
  pkg/cloud/services/compute/referenced_resources_test.go
  pkg/cloud/services/compute/servergroup.go
  pkg/cloud/services/compute/servergroup_test.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
  pkg/cloud/services/networking/floatingip.go
  pkg/cloud/services/networking/floatingip_test.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/network_test.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
  pkg/cloud/services/networking/router.go
  pkg/cloud/services/networking/router_test.go
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/networking/securitygroups_test.go
  pkg/cloud/services/networking/service.go
  pkg/cloud/services/networking/trunk.go
  pkg/cloud/services/networking/trunk_test.go
  pkg/scope/mock.go
  pkg/scope/provider.go
  pkg/scope/scope.go
  pkg/utils/errors/errors.go
  pkg/utils/filterconvert/convert.go
  test/e2e/shared/openstack.go
  test/e2e/suites/e2e/e2e_suite_test.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#2135 🌱 cloud: Better error message on image lookup failure
  pkg/cloud/services/compute/instance.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#2138 :bug: Fix down-conversion of IdentityRef
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha6/openstackmachine_conversion.go
  api/v1alpha6/types_conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/types_conversion.go
  test/e2e/suites/apivalidations/openstackcluster_test.go
  test/e2e/suites/apivalidations/openstackmachine_test.go
  test/e2e/suites/apivalidations/suite_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#2139 :bug: Fix down-conversion of IdentityRef
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha6/openstackmachine_conversion.go
  api/v1alpha6/types_conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/types_conversion.go
  test/e2e/suites/apivalidations/openstackcluster_test.go
  test/e2e/suites/apivalidations/openstackmachine_test.go
  test/e2e/suites/apivalidations/suite_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#2143 🐛 Ensure tools deps aren't older than CAPO deps
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#2145 🐛 e2e: Fix deletion of test security group
  test/e2e/shared/openstack.go
  test/e2e/suites/e2e/e2e_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#2147 🐛 e2e: Only dump resources on node 1
  test/e2e/suites/e2e/e2e_suite_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#2067 ✨ New CRD + controller for OpenStackServer (v1alpha1)
  PROJECT
  api/v1alpha1/conditions_consts.go
  api/v1alpha1/openstackserver_types.go
  api/v1alpha1/types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api_violations.report
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackservers.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  controllers/openstackmachine_controller.go
  controllers/openstackmachine_controller_test.go
  controllers/openstackserver_controller.go
  controllers/openstackserver_controller_test.go
  controllers/suite_test.go
  docs/book/src/api/v1alpha1/api.md
  docs/book/src/clusteropenstack/configuration.md
  docs/book/src/development/development.md
  hack/codegen/openapi/zz_generated.openapi.go
  main.go
  pkg/cloud/services/compute/referenced_resources.go
  pkg/cloud/services/compute/referenced_resources_test.go
  pkg/cloud/services/compute/server_resources.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
  pkg/generated/applyconfiguration/api/v1alpha1/openstackserver.go
  pkg/generated/applyconfiguration/api/v1alpha1/openstackserverspec.go
  pkg/generated/applyconfiguration/api/v1alpha1/openstackserverstatus.go
  pkg/generated/applyconfiguration/api/v1alpha1/resolvedserverspec.go
  pkg/generated/applyconfiguration/api/v1alpha1/serverresources.go
  pkg/generated/applyconfiguration/internal/internal.go
  pkg/generated/applyconfiguration/utils.go
  pkg/webhooks/fuzz_test.go
  pkg/webhooks/openstackserver_webhook.go
  pkg/webhooks/openstackserver_webhook_test.go
  pkg/webhooks/register.go
  test/e2e/suites/apivalidations/openstackserver_test.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#2021 🌱 Add design doc for OpenStackServer
  design/proposed/2020-openstackserver-controller.md
Labels: cncf-cla: yes, approved, size/L, lgtm
