Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2024-03, with the labels that each got.

#1916 🐛 ci: fix upgrades by dropping cloudName
  test/e2e/data/kustomize/k8s-upgrade/upgrade-from-template.yaml
  test/e2e/data/kustomize/k8s-upgrade/upgrade-to-template.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1909 Transform neutron filter tags into lists
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/conversion.go
  api/v1alpha7/conversion_test.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/filter_convert.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  controllers/openstackcluster_controller.go
  docs/book/src/api/v1beta1/api.md
  docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1918 🐛 Make LB additional ports security-group generation are dynamic
  pkg/cloud/services/networking/securitygroups_rules.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1923 🌱 Split v1alpha6 & v1alpha7 conversion into multiple files
  api/v1alpha6/conversion.go
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha6/openstackclustertemplate_conversion.go
  api/v1alpha6/openstackmachine_conversion.go
  api/v1alpha6/openstackmachinetemplate_conversion.go
  api/v1alpha6/types_conversion.go
  api/v1alpha7/conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/openstackclustertemplate_conversion.go
  api/v1alpha7/openstackmachine_conversion.go
  api/v1alpha7/openstackmachinetemplate_conversion.go
  api/v1alpha7/types_conversion.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1925 ⚠️ Simplify v1alpha6 cluster restorer
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha6/openstackclustertemplate_conversion.go
  api/v1alpha6/types_conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/openstackmachine_conversion.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1928 Fix CRD generation
  Makefile
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1929 🌱 Allow generating api-docs for individual versions
  Makefile
Labels: size/S, cncf-cla: yes, approved, lgtm

#1934 ⚠️ Rename fields to correctly do uppercase acronyms
  api/v1beta1/openstackcluster_types.go
  api/v1beta1/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  docs/book/src/api/v1beta1/api.md
  docs/book/src/clusteropenstack/configuration.md
  docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md
Labels: cncf-cla: yes, approved, size/L, lgtm

#1932 🐛 CI: Specify external network by name
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/kustomize/common-patches/externalNetworkByName/kustomization.yaml
  test/e2e/data/kustomize/default/kustomization.yaml
  test/e2e/data/kustomize/flatcar-sysext/kustomization.yaml
  test/e2e/data/kustomize/flatcar/kustomization.yaml
  test/e2e/data/kustomize/v1alpha6/kustomization.yaml
  test/e2e/data/kustomize/v1alpha7/kustomization.yaml
  test/e2e/data/kustomize/without-lb/kustomization.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#1935 ✨ Add junit output to e2e tests
  Makefile
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1930 ⚠️ OpenStackCluster api general cleanup
  api/v1alpha5/conversion.go
  api/v1alpha5/conversion_test.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/types_conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/openstackcluster_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  controllers/openstackmachine_controller.go
  docs/book/src/api/v1beta1/api.md
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
  pkg/cloud/services/networking/floatingip.go
  pkg/cloud/services/networking/floatingip_test.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/network_test.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/securitygroups.go
  pkg/utils/filterconvert/convert.go
  pkg/utils/optional/conversion.go
  pkg/utils/optional/types.go
  pkg/webhooks/openstackcluster_webhook.go
  pkg/webhooks/openstackcluster_webhook_test.go
  test/e2e/suites/apivalidations/neutronfilters_test.go
  test/e2e/suites/apivalidations/openstackcluster_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1937 ⚠️ Cleanup APILoadBalancer
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/openstackcluster_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  controllers/openstackcluster_controller.go
  docs/book/src/api/v1beta1/api.md
  docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
  pkg/cloud/services/networking/securitygroups.go
  pkg/webhooks/openstackcluster_webhook_test.go
  test/e2e/suites/apivalidations/openstackcluster_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1949 🐛 v1alpha5: Fix panic in conversion when port has no binding profile
  api/v1alpha5/conversion.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#1939 ⚠️ ImageFilter - add exclusive validation -> pointers
  api/v1alpha5/conversion.go
  api/v1alpha6/openstackmachine_conversion.go
  api/v1alpha7/openstackmachine_conversion.go
  api/v1beta1/openstackmachine_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  controllers/openstackmachine_controller_test.go
  docs/book/src/api/v1beta1/api.md
  docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/referenced_resources_test.go
  pkg/utils/filterconvert/convert.go
  pkg/webhooks/openstackcluster_webhook_test.go
  pkg/webhooks/openstackmachinetemplate_webhook_test.go
  test/e2e/suites/apivalidations/filters_test.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1762 ✨ Adds IPAM support for floating ips in OpenStackMachine
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/openstackmachine_conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackmachine_conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/conditions_consts.go
  api/v1beta1/openstackmachine_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  config/rbac/role.yaml
  controllers/openstackmachine_controller.go
  docs/book/src/api/v1beta1/api.md
  docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md
  pkg/cloud/services/networking/port.go
  pkg/utils/names/names.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#1936 test: bump Flatcar version
  hack/ci/cloud-init/controller.yaml.tpl
  kustomize/v1alpha7/flatcar-sysext/patch-flatcar.yaml
  kustomize/v1alpha7/flatcar/patch-flatcar.yaml
  kustomize/v1beta1/flatcar-sysext/patch-flatcar.yaml
  kustomize/v1beta1/flatcar/patch-flatcar.yaml
  templates/cluster-template-flatcar-sysext.yaml
  templates/cluster-template-flatcar.yaml
  test/e2e/data/e2e_conf.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#1941 🐛 Fix port name after port creation failure
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1955 🐛 Fix a race when updating status before reconcile completes
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1944 🌱 Deduplicate AdoptMachinePorts and AdoptBastionPorts
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/compute/dependent_resources.go
  pkg/cloud/services/compute/dependent_resources_test.go
  pkg/cloud/services/compute/referenced_resources.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#1957 ⚠️ Remove security group rules from status
  api/v1alpha5/conversion.go
  api/v1alpha6/types_conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/types_conversion.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  docs/book/src/api/v1beta1/api.md
  go.mod
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/networking/securitygroups_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1963 🌱 Add .gitattributes to identify generated files to GitHub
  .gitattributes
Labels: size/S, cncf-cla: yes, approved, lgtm

#1962 🌱 Update FloatingIPPool to use v1beta1
  api/v1alpha1/openstackfloatingippool_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackfloatingippools.yaml
  controllers/openstackfloatingippool_controller.go
  pkg/scope/provider.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1964 🐛 Fix server metadata length validation
  api/v1beta1/openstackmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  docs/book/src/api/v1beta1/api.md
  test/e2e/suites/apivalidations/openstackmachine_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1959 ⚠️ Bastion cleanup
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha6/openstackmachine_conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/openstackmachine_conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  docs/book/src/api/v1beta1/api.md
  docs/book/src/clusteropenstack/configuration.md
  docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md
  pkg/cloud/services/compute/instance_types.go
  pkg/webhooks/openstackcluster_webhook_test.go
  test/e2e/data/kustomize/common-patches/cni/patch-cluster.yaml
  test/e2e/data/kustomize/v1alpha6/bastion.yaml
  test/e2e/data/kustomize/v1alpha7/bastion.yaml
  test/e2e/suites/apivalidations/openstackcluster_test.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1966 🐛 Revert accidental update to previous API templates
  test/e2e/data/kustomize/v1alpha6/bastion.yaml
  test/e2e/data/kustomize/v1alpha7/bastion.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1951 ⚠️ Store []ResolvedPortSpec in ReferencedMachineResources
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/types_conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/openstackmachine_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  controllers/openstackmachine_controller.go
  controllers/openstackmachine_controller_test.go
  docs/book/src/api/v1beta1/api.md
  pkg/cloud/services/compute/dependent_resources.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/instance_types.go
  pkg/cloud/services/compute/referenced_resources.go
  pkg/cloud/services/compute/referenced_resources_test.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/networking/floatingip.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/network_test.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
  pkg/cloud/services/networking/router.go
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/networking/securitygroups_test.go
  pkg/cloud/services/networking/trunk.go
  pkg/cloud/services/networking/trunk_test.go
  pkg/utils/names/names.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#1965 🌱 Rename referencedResources and dependentResources
  api/v1alpha5/conversion.go
  api/v1alpha5/conversion_test.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha6/openstackmachine_conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/openstackmachine_conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/openstackmachine_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  controllers/openstackmachine_controller.go
  controllers/openstackmachine_controller_test.go
  docs/book/src/api/v1beta1/api.md
  pkg/cloud/services/compute/machine_resources.go
  pkg/cloud/services/compute/referenced_resources.go
  pkg/cloud/services/compute/referenced_resources_test.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1967 ⚠️ Resolved and Resources become optional pointer types
  api/v1alpha5/conversion_test.go
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha6/openstackmachine_conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/openstackmachine_conversion.go
  api/v1beta1/openstackmachine_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  controllers/openstackmachine_controller.go
  controllers/openstackmachine_controller_test.go
  docs/book/src/api/v1beta1/api.md
  pkg/cloud/services/compute/machine_resources.go
  pkg/cloud/services/compute/referenced_resources_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1972 ⚠️ NetworkFilter to NetworkParam
  api/v1alpha1/openstackfloatingippool_types.go
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha6/openstackmachine_conversion.go
  api/v1alpha6/types_conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/types_conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/openstackcluster_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackfloatingippools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  controllers/openstackfloatingippool_controller.go
  docs/book/src/api/v1beta1/api.md
  pkg/cloud/services/compute/referenced_resources_test.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/network_test.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
  pkg/utils/filterconvert/convert.go
  test/e2e/data/kustomize/common-patches/externalNetworkByName/kustomization.yaml
  test/e2e/suites/apivalidations/filters_test.go
  test/helpers/fuzzerfuncs.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#1974 ⚠️SecurityGroupFilter to SecurityGroupParam
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/openstackmachine_conversion.go
  api/v1alpha6/types_conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackmachine_conversion.go
  api/v1alpha7/types_conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/openstackmachine_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  controllers/openstackmachine_controller_test.go
  docs/book/src/api/v1beta1/api.md
  pkg/cloud/services/networking/port_test.go
  pkg/cloud/services/networking/securitygroups.go
  pkg/utils/filterconvert/convert.go
  test/e2e/suites/apivalidations/filters_test.go
  test/e2e/suites/e2e/e2e_test.go
  test/helpers/fuzzerfuncs.go
Labels: cncf-cla: yes, approved, size/L, lgtm
