Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2024-11, with the labels that each got.

#2217 🌱 Use Dependabot for go.mod & GH workflows
  .github/dependabot.yml
  .github/workflows/pr-dependabot.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#2219 dependabot: config changes
  .github/dependabot.yml
Labels: size/M, cncf-cla: yes, approved, lgtm

#2238 🐛 Drop caBundle from CRDs to support Kubernetes 1.31
  config/crd/patches/webhook_in_openstackclusters.yaml
  config/crd/patches/webhook_in_openstackclustertemplates.yaml
  config/crd/patches/webhook_in_openstackfloatingippools.yaml
  config/crd/patches/webhook_in_openstackmachines.yaml
  config/crd/patches/webhook_in_openstackmachinetemplates.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#2241 🌱 Bump CAPI to v1.8.5
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/data/e2e_conf.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#2242 🌱 [manual-backport-0.11] Bump CAPI to v1.8.5
  go.mod
  go.sum
  hack/codegen/go.mod
  hack/codegen/go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/data/e2e_conf.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#2253 :seedling: test/e2e: bump Flatcar image to latest Stable
  test/e2e/data/e2e_conf.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2262 🌱 Add libvirt resource type for create_devstack.sh
  hack/ci/create_devstack.sh
  hack/ci/libvirt.sh
Labels: cncf-cla: yes, approved, size/L, lgtm

#2261 🐛 Better checks before creating Floating IPs
  api/v1beta1/openstackcluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  docs/book/src/clusteropenstack/configuration.md
  pkg/cloud/services/networking/floatingip.go
  test/e2e/suites/apivalidations/openstackcluster_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#2270 [release-0.10] 🐛 Better checks before creating Floating IPs
  api/v1beta1/openstackcluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  docs/book/src/clusteropenstack/configuration.md
  pkg/cloud/services/networking/floatingip.go
  test/e2e/suites/apivalidations/openstackcluster_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#2285 🌱 Dependabot conf changes
  .github/dependabot.yml
Labels: size/S, cncf-cla: yes, approved, lgtm

#2268 📖 Add section on support and guarantees
  CONTRIBUTING.md
Labels: size/M, cncf-cla: yes, approved, lgtm

#1567 ✨ Flexible Nova microversions
  pkg/clients/compute.go
  pkg/clients/mock/compute.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/utils/openstack/microversion.go
  pkg/utils/openstack/microversion_test.go
  test/e2e/shared/openstack.go
Labels: cncf-cla: yes, approved, size/L, lgtm
