Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2024-10, with the labels that each got.

#2189 🌱 Bump controller-tools to v0.16.4
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackfloatingippools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackservers.yaml
  config/rbac/role.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  orc/Makefile
  orc/config/crd/bases/openstack.k-orc.cloud_images.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#2191 🐛 Re-allow `OpenStackMachine` to use their own `IdentityRef`
  controllers/openstackmachine_controller.go
  pkg/scope/provider.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#2182 Reduce reconciles and logs
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  controllers/openstackserver_controller.go
  pkg/cloud/services/networking/securitygroups.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#2148 :sparkles: Support Flavor IDs
  api/v1alpha1/openstackserver_types.go
  api/v1alpha1/types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/openstackmachine_types.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha6/zz_generated.deepcopy.go
  api/v1alpha7/conversion_test.go
  api/v1alpha7/openstackmachine_types.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1alpha7/zz_generated.deepcopy.go
  api/v1beta1/openstackmachine_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackservers.yaml
  controllers/openstackcluster_controller_test.go
  controllers/openstackmachine_controller_test.go
  controllers/openstackserver_controller.go
  controllers/openstackserver_controller_test.go
  docs/book/src/api/v1alpha1/api.md
  docs/book/src/api/v1alpha6/api.md
  docs/book/src/api/v1alpha7/api.md
  docs/book/src/api/v1beta1/api.md
  hack/codegen/openapi/zz_generated.openapi.go
  pkg/clients/compute.go
  pkg/clients/mock/compute.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/instance_types.go
  pkg/cloud/services/compute/referenced_resources.go
  pkg/cloud/services/compute/referenced_resources_test.go
  pkg/generated/applyconfiguration/api/v1alpha1/openstackserverspec.go
  pkg/generated/applyconfiguration/api/v1alpha1/resolvedserverspec.go
  pkg/generated/applyconfiguration/api/v1alpha6/openstackmachinespec.go
  pkg/generated/applyconfiguration/api/v1alpha7/openstackmachinespec.go
  pkg/generated/applyconfiguration/api/v1beta1/openstackmachinespec.go
  pkg/generated/applyconfiguration/api/v1beta1/resolvedmachinespec.go
  pkg/generated/applyconfiguration/internal/internal.go
  pkg/webhooks/openstackcluster_webhook_test.go
  pkg/webhooks/openstackmachinetemplate_webhook_test.go
  pkg/webhooks/openstackserver_webhook_test.go
  test/e2e/shared/openstack.go
  test/e2e/suites/apivalidations/filters_test.go
  test/e2e/suites/apivalidations/openstackcluster_test.go
  test/e2e/suites/apivalidations/openstackmachine_test.go
  test/e2e/suites/apivalidations/openstackserver_test.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#2192 ✨ ORC Image API update
  controllers/openstackserver_controller.go
  internal/controllers/image/controller.go
  internal/controllers/image/reconcile.go
  internal/controllers/image/status.go
  internal/controllers/image/status_test.go
  internal/controllers/image/upload.go
  internal/controllers/image/upload_test.go
  internal/controllers/image/webdownload.go
  orc/api/v1alpha1/controller_options.go
  orc/api/v1alpha1/credentials_ref.go
  orc/api/v1alpha1/image_types.go
  orc/api/v1alpha1/zz_generated.deepcopy.go
  orc/config/crd/bases/openstack.k-orc.cloud_images.yaml
  orc/hack/codegen/openapi/zz_generated.openapi.go
  orc/pkg/clients/applyconfiguration/api/v1alpha1/cloudcredentialsreference.go
  orc/pkg/clients/applyconfiguration/api/v1alpha1/controlleroptions.go
  orc/pkg/clients/applyconfiguration/api/v1alpha1/imagecontent.go
  orc/pkg/clients/applyconfiguration/api/v1alpha1/imagecontentsourcedownload.go
  orc/pkg/clients/applyconfiguration/api/v1alpha1/imagefilter.go
  orc/pkg/clients/applyconfiguration/api/v1alpha1/imageimport.go
  orc/pkg/clients/applyconfiguration/api/v1alpha1/imageresourcespec.go
  orc/pkg/clients/applyconfiguration/api/v1alpha1/imageresourcestatus.go
  orc/pkg/clients/applyconfiguration/api/v1alpha1/imagespec.go
  orc/pkg/clients/applyconfiguration/api/v1alpha1/imagestatus.go
  orc/pkg/clients/applyconfiguration/api/v1alpha1/managedoptions.go
  orc/pkg/clients/applyconfiguration/internal/internal.go
  orc/pkg/clients/applyconfiguration/utils.go
  orc/test/apivalidations/image_test.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/referenced_resources.go
  pkg/cloud/services/compute/referenced_resources_test.go
  pkg/utils/orc/identity_ref.go
  test/e2e/data/kustomize/common-patches/images/images.yaml
  test/e2e/data/kustomize/flatcar-sysext/kustomization.yaml
  test/e2e/data/kustomize/flatcar/kustomization.yaml
  test/e2e/shared/images.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#2193 feat(manager): :sparkles: add region to openStackMachineSpec.ProviderID field from crd identityRef
  api/v1alpha6/conversion_test.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/conversion_test.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/identity_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackfloatingippools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackservers.yaml
  controllers/openstackmachine_controller.go
  docs/book/src/api/v1beta1/api.md
  hack/codegen/openapi/zz_generated.openapi.go
  pkg/generated/applyconfiguration/api/v1beta1/openstackidentityreference.go
  pkg/generated/applyconfiguration/internal/internal.go
  pkg/scope/provider.go
  test/e2e/shared/openstack.go
  test/e2e/suites/apivalidations/openstackmachine_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#2197 🌱 image: Fix various immutability validations
  internal/controllers/image/reconcile.go
  orc/api/v1alpha1/image_types.go
  orc/api/v1alpha1/zz_generated.deepcopy.go
  orc/config/crd/bases/openstack.k-orc.cloud_images.yaml
  orc/test/apivalidations/image_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#2198 ✨ Bump version artifacts for release-0.11
  metadata.yaml
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2195 🌱 refactoring: Untangle four image-fetching strategies
  internal/controllers/image/reconcile.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#2199 🌱 Remove pkg/utils/hash
  pkg/cloud/services/compute/instance.go
  pkg/scope/hash.go
  pkg/scope/provider.go
  pkg/utils/conversion/restore.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#2200 🌱 Fix verification of generated files
  Makefile
  go.sum
  hack/codegen/go.mod
  hack/codegen/go.sum
  orc/Makefile
  orc/go.mod
  orc/go.sum
  orc/hack/codegen/go.mod
  orc/hack/codegen/go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm

#2194 🌱 ORC: Move image controller into ORC
  Makefile
  go.mod
  go.sum
  hack/codegen/go.mod
  hack/codegen/go.sum
  hack/codegen/go.work.sum
  hack/tools/go.mod
  hack/tools/go.sum
  internal/util/ssa/applyconfigpatch.go
  main.go
  orc/Makefile
  orc/config/rbac/role.yaml
  orc/go.mod
  orc/go.sum
  orc/hack/codegen/go.mod
  orc/hack/codegen/go.sum
  orc/hack/codegen/go.work.sum
  orc/internal/controllers/export/setup.go
  orc/internal/controllers/image/controller.go
  orc/internal/controllers/image/reconcile.go
  orc/internal/controllers/image/status.go
  orc/internal/controllers/image/status_test.go
  orc/internal/controllers/image/suite_test.go
  orc/internal/controllers/image/testdata/README.md
  orc/internal/controllers/image/testdata/raw.img
  orc/internal/controllers/image/testdata/raw.img.bz2
  orc/internal/controllers/image/testdata/raw.img.gz
  orc/internal/controllers/image/testdata/raw.img.xz
  orc/internal/controllers/image/upload.go
  orc/internal/controllers/image/upload_helpers.go
  orc/internal/controllers/image/upload_test.go
  orc/internal/controllers/image/webdownload.go
  orc/internal/osclients/compute.go
  orc/internal/osclients/image.go
  orc/internal/osclients/loadbalancer.go
  orc/internal/osclients/mock/compute.go
  orc/internal/osclients/mock/doc.go
  orc/internal/osclients/mock/image.go
  orc/internal/osclients/mock/loadbalancer.go
  orc/internal/osclients/mock/networking.go
  orc/internal/osclients/mock/volume.go
  orc/internal/osclients/networking.go
  orc/internal/osclients/volume.go
  orc/internal/scope/hash.go
  orc/internal/scope/mock.go
  orc/internal/scope/provider.go
  orc/internal/scope/scope.go
  orc/internal/util/errors/errors.go
  orc/internal/util/errors/terminal.go
  orc/internal/util/ssa/applyconfigpatch.go
  orc/internal/util/ssa/conditions.go
  orc/internal/version/version.go
  orc/pkg/controllers/alias.go
  orc/test/apivalidations/suite_test.go
  test/e2e/shared/images.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#2203 🌱 ORC: Generate common parts of resource API
  orc/Makefile
  orc/api/v1alpha1/image_types.go
  orc/api/v1alpha1/zz_generated.deepcopy.go
  orc/api/v1alpha1/zz_generated.image-resource.go
  orc/cmd/manager/main.go
  orc/cmd/resource-generator/data/api.template
  orc/cmd/resource-generator/main.go
  orc/config/crd/bases/openstack.k-orc.cloud_images.yaml
  orc/hack/codegen/openapi/zz_generated.openapi.go
  orc/pkg/clients/applyconfiguration/api/v1alpha1/doc.go
  orc/pkg/clients/applyconfiguration/api/v1alpha1/imagestatus.go
  orc/pkg/clients/applyconfiguration/api/v1alpha1/imagestatusextra.go
  orc/pkg/clients/applyconfiguration/utils.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#2179 🐛 Fix ServerMetadata Not Applied to Bastion in OpenStackCluster
  controllers/openstackcluster_controller.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#2215 ✨ Bump CAPI to v1.8.4
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/data/e2e_conf.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm
