Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2024-04, with the labels that each got.

#1987 🐛 Fix v1alpha7 machine restorer and test
  api/v1alpha7/conversion_test.go
  api/v1alpha7/openstackmachine_conversion.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#1990 ⚠️ Bastion is enabled by default if specified
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  docs/book/src/api/v1beta1/api.md
  docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/networking/securitygroups_test.go
  pkg/webhooks/openstackcluster_webhook.go
  pkg/webhooks/openstackcluster_webhook_test.go
  test/e2e/suites/apivalidations/openstackcluster_test.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1988 ⚠️ Move InstanceID from Spec to Status
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha6/openstackmachine_conversion.go
  api/v1alpha6/openstackmachinetemplate_conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/conversion_test.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/openstackmachine_conversion.go
  api/v1alpha7/openstackmachinetemplate_conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/openstackmachine_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  controllers/openstackmachine_controller.go
  controllers/suite_test.go
  docs/book/src/api/v1beta1/api.md
Labels: cncf-cla: yes, approved, size/L, lgtm

#1989 🐛 Fix multiple panics in restore functions
  api/v1alpha6/conversion_test.go
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha6/types_conversion.go
  api/v1alpha7/conversion_test.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/types_conversion.go
  test/helpers/fuzz_restorer.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1982 📖 Document changes to Filters
  docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md
Labels: size/M, cncf-cla: yes, approved, lgtm

#1993 ✨ Add API docs for v1alpha1
  Makefile
  api/v1alpha1/doc.go
  docs/book/gen-crd-api-reference-docs/config.json
  docs/book/src/SUMMARY.md
  docs/book/src/api/v1alpha1/api.md
  docs/book/src/api/v1alpha6/api.md
  docs/book/src/api/v1alpha7/api.md
  docs/book/src/api/v1beta1/api.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1994 🌱 Bump version artifacts for release-0.10
  metadata.yaml
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1992 🌱 Remove legacy v1alpha7 filterconvert utils
  pkg/utils/filterconvert/v1alpha7/convert.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#2000 🐛 Rules are optional in security group rules before v1beta1
  api/v1alpha5/types.go
  api/v1alpha6/types.go
  api/v1alpha7/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1998 🐛 Make floatingIPNetwork a pointer and if there's only one external network use it as default
  api/v1alpha1/conditions_consts.go
  api/v1alpha1/openstackfloatingippool_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1beta1/conditions_consts.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackfloatingippools.yaml
  controllers/openstackfloatingippool_controller.go
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#2001 🌱 Minor improvements to api validation tests
  Makefile
  test/e2e/suites/apivalidations/openstackcluster_test.go
  test/e2e/suites/apivalidations/suite_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1922 feat: add configurable loadbalancer network
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  controllers/openstackcluster_controller.go
  docs/book/src/api/v1beta1/api.md
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#1996 🐛 Include more device_owners when looking for a port for floating ip
  pkg/cloud/services/networking/port.go
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#2010 🌱 Cleanup security group created by e2e test
  test/e2e/shared/openstack.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2004 Add opt to use AZ for APISeverLoadBalancer
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha6/types_conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/conversion_test.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1alpha7/types_conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  docs/book/src/api/v1beta1/api.md
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#2014 🌱 Bump k8s dep to 0.29.3
  api/v1alpha5/conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/openstackmachine_types.go
  api/v1alpha6/types_conversion.go
  api/v1alpha7/conversion_test.go
  api/v1alpha7/openstackmachine_types.go
  api/v1beta1/conversion.go
  api/v1beta1/openstackmachine_types.go
  api/v1beta1/types.go
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  controllers/openstackfloatingippool_controller.go
  controllers/openstackmachine_controller.go
  controllers/openstackmachine_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/referenced_resources_test.go
  pkg/cloud/services/compute/servergroup_test.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
  pkg/cloud/services/networking/floatingip.go
  pkg/cloud/services/networking/floatingip_test.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/network_test.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
  pkg/cloud/services/networking/securitygroups_test.go
  pkg/webhooks/openstackcluster_webhook.go
  pkg/webhooks/openstackcluster_webhook_test.go
  pkg/webhooks/openstackmachinetemplate_webhook_test.go
  test/e2e/suites/apivalidations/filters_test.go
  test/e2e/suites/apivalidations/openstackcluster_test.go
  test/e2e/suites/apivalidations/openstackmachine_test.go
  test/e2e/suites/conformance/conformance_test.go
  test/e2e/suites/e2e/e2e_test.go
  test/e2e/suites/e2e/remediations_test.go
  test/helpers/external/cluster.go
  test/helpers/fuzzerfuncs.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#2008 ⚠️ Allow explicitly empty volume AZ
  .golangci.yml
  Makefile
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha6/conversion_test.go
  api/v1alpha6/openstackmachine_conversion.go
  api/v1alpha6/types_conversion.go
  api/v1alpha6/zz_generated.conversion.go
  api/v1alpha7/conversion_test.go
  api/v1alpha7/openstackmachine_conversion.go
  api/v1alpha7/types_conversion.go
  api/v1alpha7/zz_generated.conversion.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  controllers/openstackmachine_controller_test.go
  docs/book/src/api/v1beta1/api.md
  docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/instance_test.go
  pkg/utils/conversioncommon/volumeavailabilityzone.go
  test/e2e/data/kustomize/multi-az/patch-machine-template-control-plane.yaml
  test/e2e/data/kustomize/multi-az/patch-machine-template-worker.yaml
  test/e2e/suites/apivalidations/openstackmachine_test.go
  test/helpers/fuzzerfuncs.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#2011 🐛 Fix idempotent restore when setting ControlPlaneEndpoint
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  test/e2e/suites/apivalidations/filters_test.go
  test/e2e/suites/apivalidations/openstackcluster_test.go
  test/e2e/suites/apivalidations/suite_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#2017 🐛 Fix crash on delete with no bastion
  Makefile
  controllers/openstackcluster_controller.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/compute/instance.go
  test/e2e/data/kustomize/no-bastion/kustomization.yaml
  test/e2e/data/kustomize/no-bastion/patch-no-bastion.yaml
  test/e2e/shared/common.go
  test/e2e/shared/defaults.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#2005 :seedling: Ensure E2E cleanup
  test/e2e/shared/openstack.go
  test/e2e/suites/e2e/e2e_suite_test.go
  test/e2e/suites/e2e/idmatcher_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#2022 ⚠️ Remove v1alpha5
  .golangci.yml
  Makefile
  PROJECT
  README.md
  api/v1alpha5/conversion.go
  api/v1alpha5/conversion_test.go
  api/v1alpha5/doc.go
  api/v1alpha5/groupversion_info.go
  api/v1alpha5/identity_types.go
  api/v1alpha5/openstackcluster_types.go
  api/v1alpha5/openstackclustertemplate_types.go
  api/v1alpha5/openstackmachine_types.go
  api/v1alpha5/openstackmachinetemplate_types.go
  api/v1alpha5/types.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha5/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  config/crd/kustomization.yaml
  kustomize/v1alpha5/default/cluster-template.yaml
  kustomize/v1alpha5/default/kustomization.yaml
  kustomize/v1alpha5/external-cloud-provider/kustomization.yaml
  kustomize/v1alpha5/external-cloud-provider/patch-ccm.yaml
  kustomize/v1alpha5/without-lb/kustomization.yaml
  kustomize/v1alpha5/without-lb/patch-without-lb.yaml
  main.go
  test/e2e/suites/apivalidations/suite_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#2028 🐛 Fix v1alpha7 e2e tests
  test/e2e/data/kustomize/v1alpha7/kustomization.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#2032 📖 remove outdated warnings
  docs/book/src/topics/crd-changes/v1alpha6-to-v1alpha7.md
  docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#2037 :seedling: Refactoring: never assign unacceptable TLS versions
  main.go
  main_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#2026 ⚠️ Deprecate v1alpha7
  api/v1alpha7/openstackcluster_types.go
  api/v1alpha7/openstackclustertemplate_types.go
  api/v1alpha7/openstackmachine_types.go
  api/v1alpha7/openstackmachinetemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  docs/book/src/api/v1alpha7/api.md
  test/e2e/suites/apivalidations/openstackcluster_test.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#1565 📖 Proposal for microversion support
  docs/proposals/20230525-openstack-microversion-support.md
Labels: cncf-cla: yes, approved, size/L, lgtm

#2043 🐛 Fix webhook panic when adding managed security groups
  pkg/webhooks/fuzz_test.go
  pkg/webhooks/openstackcluster_webhook.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#2045 🌱 Bump Golang CI Lint to v1.57.2
  .golangci.yml
  api/v1alpha6/conversion_test.go
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  controllers/openstackcluster_controller_test.go
  controllers/openstackfloatingippool_controller.go
  controllers/openstackmachine_controller_test.go
  controllers/suite_test.go
  hack/tools/Makefile
  main_test.go
  pkg/cloud/services/compute/instance_test.go
  pkg/cloud/services/compute/instance_types_test.go
  pkg/cloud/services/compute/referenced_resources_test.go
  pkg/cloud/services/compute/servergroup_test.go
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
  pkg/cloud/services/networking/floatingip_test.go
  pkg/cloud/services/networking/network_test.go
  pkg/cloud/services/networking/port_test.go
  pkg/cloud/services/networking/router_test.go
  pkg/cloud/services/networking/securitygroups_test.go
  pkg/cloud/services/networking/trunk_test.go
  pkg/webhooks/openstackcluster_webhook_test.go
  pkg/webhooks/openstackmachinetemplate_webhook_test.go
  test/e2e/shared/exec.go
  test/e2e/shared/exec_test.go
  test/helpers/fuzzerfuncs.go
Labels: cncf-cla: yes, approved, size/L, lgtm
