Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2024-06, with the labels that each got.

#2096 🌱 Add script for API diff check
  Makefile
  scripts/ci-apidiff.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#2109 ⚠️ More than one instance found is now an error
  controllers/openstackcluster_controller.go
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/networking/network.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/router.go
  pkg/utils/errors/errors.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#2112 🐛 instance: re-add error event if server creationg returned an error
  pkg/cloud/services/compute/instance.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2114 🐛 Remove bastion security group when disabling the bastion
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/networking/securitygroups_test.go
  test/e2e/suites/e2e/e2e_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#2115 🌱Add EmilienM as a maintainer
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2099 :bug: if the openstackcluster was ready, we don't want to set a terminalError
  controllers/openstackcluster_controller.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#2120 :book: Fix dnsNameservers array in the v1beta1 changes docs
  docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#2123 📖 Document that OVSHWOffload is no longer required
  api/v1beta1/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
  docs/book/src/api/v1beta1/api.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2125 📖 Update agenda links w/ shared drive
  README.md
  docs/book/book.toml
Labels: size/S, cncf-cla: yes, approved, lgtm

#2132 🌱 IdentityRefProvider: DRY obtaining OpenStackIdentityRef
  api/v1alpha1/openstackfloatingippool_types.go
  api/v1beta1/identity_types.go
  api/v1beta1/openstackcluster_types.go
  api/v1beta1/openstackmachine_types.go
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  controllers/openstackfloatingippool_controller.go
  controllers/openstackmachine_controller.go
  docs/book/src/api/v1beta1/api.md
  pkg/scope/mock.go
  pkg/scope/provider.go
  pkg/scope/scope.go
Labels: cncf-cla: yes, approved, size/L, lgtm
