Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2025-08, with the labels that each got.

#2631 🌱 Bump oauth2
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/S, cncf-cla: yes, approved, lgtm

#2628 proposal: add new CRD OpenStackClusterIdentity
  docs/proposals/20250722-openstackclusteridentity.md
Labels: cncf-cla: yes, needs-ok-to-test, approved, size/L, lgtm

#2609 🌱 E2E: Update Calico to v3.30.2
  test/e2e/data/cni/calico.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#2645 🌱 Unify and enforce CAPI import aliases
  .golangci.yml
  api/v1alpha1/openstackfloatingippool_types.go
  api/v1alpha1/openstackserver_types.go
  api/v1beta1/conditions_consts.go
  api/v1beta1/openstackcluster_types.go
  api/v1beta1/openstackmachine_types.go
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  controllers/openstackfloatingippool_controller.go
  controllers/openstackmachine_controller.go
  controllers/openstackserver_controller.go
  controllers/openstackserver_controller_test.go
  pkg/cloud/services/loadbalancer/loadbalancer_test.go
  test/e2e/shared/defaults.go
  test/e2e/suites/apivalidations/openstackcluster_test.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#2656 🌱 Add metadata for v0.13 and v1beta2 contract
  config/crd/kustomization.yaml
  metadata.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2668 🌱 Bump golangci-lint to v2
  .golangci.yml
  Makefile
  controllers/openstackfloatingippool_controller.go
  controllers/openstackmachine_controller.go
  controllers/openstackserver_controller.go
  hack/tools/Makefile
  pkg/cloud/services/compute/instance.go
  pkg/cloud/services/compute/referenced_resources.go
  test/e2e/shared/common.go
Labels: cncf-cla: yes, approved, size/L, lgtm
