Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2025-01, with the labels that each got.

#2353 🌱 Support for additional controlplane and worker secgroup rules
  api/v1alpha6/openstackcluster_conversion.go
  api/v1alpha7/openstackcluster_conversion.go
  api/v1beta1/openstackcluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  cmd/models-schema/zz_generated.openapi.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  docs/book/src/api/v1beta1/api.md
  docs/book/src/clusteropenstack/configuration.md
  pkg/cloud/services/networking/securitygroups.go
  pkg/cloud/services/networking/securitygroups_test.go
  pkg/generated/applyconfiguration/api/v1beta1/managedsecuritygroups.go
  pkg/generated/applyconfiguration/internal/internal.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#2352 :bug: New IPAddressClaim.ObjectMeta.Labels nil map assign panic
  controllers/openstackserver_controller.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#2357 🌱 Conformance: Fix warnings
  Dockerfile
  test/e2e/data/kubetest/conformance-fast.yaml
  test/e2e/data/kubetest/conformance.yaml
  test/e2e/suites/conformance/conformance_suite_test.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#2339 🐛 fix: create lbaas in specified subnet
  controllers/openstackcluster_controller.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#2355 🌱 e2e: bump to ubuntu-2404-kube-v1.31.2
  test/e2e/data/e2e_conf.yaml
  test/e2e/shared/images.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#2337 ✨ feat: use specified go version for docker build
  Dockerfile
  Makefile
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#2368 🌱 E2E: Collect console log from machines
  pkg/clients/compute.go
  pkg/clients/mock/compute.go
  test/e2e/shared/common.go
  test/e2e/shared/openstack.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#2371 [release-0.10] 🐛 fix: create lbaas in specified subnet
  controllers/openstackcluster_controller.go
  pkg/cloud/services/loadbalancer/loadbalancer.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#2367 🌱 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2370 🌱 Use the same version of Go everywhere (latest: 1.23.4)
  .golangci.yml
  Dockerfile
  Makefile
  go.mod
  hack/tools/go.mod
  netlify.toml
Labels: size/S, cncf-cla: yes, approved, lgtm

#2378 🌱 dependabot: skip code-generator updates on 0.11
  .github/dependabot.yml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2338 ✨ feat: reconcile pre-existing router
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  pkg/cloud/services/networking/router.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#2376 📖 Add Image templates, improve dev-test clusterclass and update dev docs
  docs/book/src/development/development.md
  templates/cluster-template-development.yaml
  templates/clusterclass-dev-test.yaml
  templates/images-template.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#2388 🌱 hack/tools: bump gotestsum and golangci to latest tags
  hack/tools/Makefile
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2256 :bug: Ensure that existing ports also have correct tags and trunks
  controllers/openstackserver_controller.go
  controllers/openstackserver_controller_test.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
  pkg/cloud/services/networking/service.go
  test/e2e/data/e2e_conf.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#2356 🐛 Ensure that existing ports also have correct tags and trunks
  controllers/openstackcluster_controller.go
  controllers/openstackcluster_controller_test.go
  controllers/openstackmachine_controller.go
  pkg/cloud/services/networking/port.go
  pkg/cloud/services/networking/port_test.go
  pkg/cloud/services/networking/service.go
  test/e2e/data/e2e_conf.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#2399 🌱 Release: Include ClusterClasses and Images templates
  Makefile
  docs/book/src/development/development.md
  templates/image-template-bastion.yaml
  templates/image-template-node.yaml
  templates/images-template.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#2402 🐛 Stop printing InstanceState for OpenStackMachine
  api/v1beta1/openstackmachine_types.go
  cmd/models-schema/zz_generated.openapi.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  docs/book/src/api/v1beta1/api.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2409 [release-0.12] port/cleanup: support old bastion port name
  pkg/cloud/services/networking/port.go
Labels: cncf-cla: yes, approved, size/XS, lgtm
