Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2025-05, with the labels that each got.

#2531 🌱 Bump cloud-build image to support go 1.23
  cloudbuild.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#2533 🌱 Bump CAPI to v1.10.1
  Makefile
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/data/e2e_conf.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#2539 🌱 Bump go to 1.23.8
  Makefile
  netlify.toml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2536 🌱 Add weekly security scan using govulncheck and Trivy
  .github/workflows/security-scan.yaml
  Makefile
  hack/ensure-trivy.sh
  hack/verify-container-images.sh
Labels: cncf-cla: yes, approved, size/L, lgtm

#2542 fix: enum typo error.
  api/v1beta1/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#2553 🌱 Add weekly security scan using govulncheck and trivy
  .github/workflows/security-scan.yaml
  Makefile
  hack/ensure-trivy.sh
  hack/verify-container-images.sh
Labels: cncf-cla: yes, approved, size/L, lgtm

#2558 🌱 Disable security scanning for release-0.10
  .github/workflows/security-scan.yaml
  CONTRIBUTING.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2559 🌱 Build with go1.23.8
  Makefile
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2561 🌱 E2E: clusterctl-upgrade from v0.10
  Makefile
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/kustomize/common-patches/images-without-ref/images.yaml
  test/e2e/data/kustomize/common-patches/images-without-ref/kustomization.yaml
  test/e2e/data/kustomize/without-orc/kustomization.yaml
  test/e2e/shared/defaults.go
  test/e2e/suites/e2e/clusterctl_upgrade_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#2390 🐛 fix: watch ipaddressclaim in openstackserver controller
  controllers/openstackserver_controller.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#2565 🌱 Update e2e config and clusterctl-upgrade
  Makefile
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/kustomize/without-orc/kustomization.yaml
  test/e2e/shared/defaults.go
  test/e2e/suites/e2e/clusterctl_upgrade_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#2577 📖 Fix broken link to cluster API docs
  docs/book/src/development/development.md
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test
