Repository kubernetes-sigs/cluster-api-provider-openstack, pull requests merged in 2025-03, with the labels that each got.

#2448 🌱 Bump golangci-lint to support go1.24
  hack/tools/Makefile
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2450 🌱 ci: add GH workflow to automate golangci-lint bumps
  .github/workflows/update-golangci-lint.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#2445 🌱(deps): pin crypto for stable 0.11
  .github/dependabot.yml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2457 🌱(deps): pin envsubst
  .github/dependabot.yml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2453 🌱 Fix workflows/update-golangci-lint
  .github/workflows/update-golangci-lint.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#2446 fix: allow modification of all ManagedSecurityGroups
  pkg/webhooks/openstackcluster_webhook.go
  pkg/webhooks/openstackcluster_webhook_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm, ok-to-test

#2464 :bug: fix: dereference the instance state in machine state reconcile calls
  controllers/openstackmachine_controller.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#2473 🌱 deps: skip github.com/onsi/ginkgo/v2 on release-0.11
  .github/dependabot.yml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2475 Fix panic when OpenStack server is deleted by an external agent
  api/v1beta1/conditions_consts.go
  controllers/openstackmachine_controller.go
  controllers/openstackserver_controller.go
  controllers/openstackserver_controller_test.go
  test/e2e/data/e2e_conf.yaml
  test/e2e/shared/openstack.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#2478 Don't set OSMachine Ready until all config is complete
  controllers/openstackmachine_controller.go
  test/e2e/suites/e2e/e2e_test.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#2479 ci: build e2e prerequisites in parallel
  Makefile
  hack/ci/common.sh
  hack/ci/create_devstack.sh
  scripts/ci-e2e.sh
Labels: cncf-cla: yes, approved, size/L, lgtm

#2481 Fix logging when e2e prerequisites build fails
  scripts/ci-e2e.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#2482 OpenStackServer controller: minor log message fix
  controllers/openstackserver_controller.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#2257 Do not delete bastion floating ip if set in spec
  controllers/openstackcluster_controller.go
Labels: size/S, cncf-cla: yes, approved, lgtm, ok-to-test

#2490 🌱 Bump CAPI to v1.10.0-beta.0
  Makefile
  cmd/models-schema/zz_generated.openapi.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackfloatingippools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_openstackservers.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/data/e2e_conf.yaml
  test/e2e/shared/cluster.go
  test/e2e/shared/common.go
  test/e2e/shared/images.go
  test/e2e/shared/openstack.go
  test/e2e/shared/suite.go
  test/e2e/suites/conformance/conformance_test.go
  test/e2e/suites/e2e/clusterctl_upgrade_test.go
  test/e2e/suites/e2e/e2e_suite_test.go
  test/e2e/suites/e2e/e2e_test.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#2502 🐛 fix openstackserver controller concurrency
  controllers/openstackserver_controller.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test
